### ISSUE TITLE
[BUG] Some Loot Crate rewards were broken due to updates.

### ISSUE THREAD

**Issue by Flame500** [Minecraft-Eternal/MC-Eternal-1.12#104]
**Describe the bug**
There are 8 rewards that were broken due to the 1.3.7-1.4.x update.

<itemfilters:missing>.withTag({item: {ForgeCaps: {"astralsorcery:cap_item_amulet_holder": {}}, id: "ebwizardry:armour_upgrade", Count: 1 as byte}, display: {Name: "§bebwizardry§8:§6armour_upgrade"}})
-from unclaimed black market crates

<minecraft:spawn_egg>.withTag({display: {Name: "Spawn"}, EntityTag: {id: "icbmclassic:zombie.xmas.boss"}})
-from unclaimed black market crates

<minecraft:spawn_egg>.withTag({display: {Name: "Spawn"}, EntityTag: {id: "icbmclassic:skeleton.xmas.snowman"}})
-from unclaimed black market crates

<minecraft:spawn_egg>.withTag({display: {Name: "Spawn"}, EntityTag: {id: "icbmclassic:skeleton.xmas.boss"}})
-from unclaimed black market crates

<minecraft:spawn_egg>.withTag({display: {Name: "Spawn"}, EntityTag: {id: "icbmclassic:zombie.xmas.creeper"}})
-from both common and unclaimed black market crates

<itemfilters:missing>.withTag({item: "extrautils2:soundmuffler", display: {Name: "§bextrautils2§8:§6soundmuffler"}})
-from common crates

<itemfilters:missing>.withTag({item: "cyclicmagic:corrupted_chorus", display: {Name: "§bcyclicmagic§8:§6corrupted_chorus"}})
-from common crates

<itemfilters:missing>.withTag({item: "davincisvessels:balloon", display: {Name: "§bdavincisvessels§8:§6balloon"}})
-from common crates

**Version of MC Eternal**
1.4.3

**To Reproduce**
Check the JEI for loot crate and scroll through the list of rewards.

**Expected behavior**
These should either be removed or updated to give the appropriate rewards.

**Screenshots**

**Additional context**

**Comment by anabsolutesloth** [comment]
Addressed by #226

**Comment by anabsolutesloth** [comment]
#226 has been merged, addressing this issue, closing.
