### ISSUE TITLE
[BUG] Duping iron ore 

### ISSUE THREAD

**Issue by Flamichka** [Minecraft-Eternal/MC-Eternal-1.12#107]
I updated the pack on the latest version. Now when the player destroys an ore it drops couple of some sort of iron ore chunks when the player pick em up it both turn to usual iron ore then when the player places those ore blocks he could destroy each again and get couple of iron ore chunks Dupe !
Didn't test with other types of ore just noticed and reported to you

**Comment by anabsolutesloth** [comment]
This issue should be patched next hotfix, one of Classes from LevelUp Reloaded was still granting levels in a skill that was disabled.

**Comment by cornehoskam** [comment]
Will be fixed in the next patch
