### ISSUE TITLE
Game stuttering - Memory Leaking

### ISSUE THREAD

**Issue by MassiveCrater** [Minecraft-Eternal/MC-Eternal-1.12#109]
**Describe the bug**
One or more of the mods is definitely creating a memory leak. We have forced chunk loading and have only played on the server for a day but it has reached the point where as soon as I log in the RAM usage starts at 7000 and quickly reaches the top (I have mine set at 8000) endless game stuttering. I have tried using the suggested arguments in the discord but this has not made any difference.

**Version of MC Eternal**
14.3.1

**Additional context**
Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
16 GB RAM 
GeForce RTX 2070 SUPER

**Comment by criscky** [comment]
not enough information
- What was in your inventory, equipments and baubles?
- What are you doing?
- Can you send a log and a debug from WHEN it happens

Some simple things: 
- please use args or else your gb will go nuts
- please be sure you're not using any fish's undead equipament or have it in your inventory (this is pinned in the discord server)
