### ISSUE TITLE
[HELP] Packet 0/14 (b) was larger than I expected, found 58 bytes extra whilst reading packet 14

### ISSUE THREAD

**Issue by DuanYuFi** [Minecraft-Eternal/MC-Eternal-1.12#110]
I'm running EternalMC 1.4.3.1 on Ubuntu Server and 1.4.3.1 Client on windows, however, when i login, the server report Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException. What's wrong with it? I have worked on it few hours

my forges are both 14.23.5.2854 on server and client

Full log here:
[14:19:01] [Server thread/INFO]: wdnmd[/ip:port] logged in with entity id 636 at (-176.5, 80.0, 227.5)
[14:19:01] [Server thread/INFO]: wdnmd joined the game
[14:19:05] [Server thread/INFO]: wdnmd lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/14 (b) was larger than I expected, found 58 bytes extra whilst reading packet 14
[14:19:05] [Server thread/INFO]: wdnmd left the game

**Comment by level-zero-one** [comment]
delete server.dat and try again

**Comment by DuanYuFi** [comment]
> delete server.dat and try again

sorry but i can't find file "server.dat", you mean level.dat?
[https://md.byr.ac.cn/uploads/upload_f3e511b1cfc36ed0d3facb14c42a0b71.png](url)

**Comment by DuanYuFi** [comment]
I thought it's the client's problem because I couldn't enter another Eternal Server too. However, I can play in my local windows server. That's strange.

My Ubuntu is Ubuntu 18.04

**Comment by DuanYuFi** [comment]
> delete server.dat and try again

I tried it and still same wrong

**Comment by criscky** [comment]
what launcher are you using?
what is the version of the pack?
can you send the latest.log, please? (dont send file, send a pastebin)
also you prob gonna receive more help if you ask that in discord, in git issues we try to work with issues in the pack, not individual issues

**Comment by DuanYuFi** [comment]
> what launcher are you using?
> what is the version of the pack?
> can you send the latest.log, please? (dont send file, send a pastebin)
> also you prob gonna receive more help if you ask that in discord, in git issues we try to work with issues in the pack, not individual issues

Sorry I'm new in github. Very appreciate for your help and advice. I have solved my problem. Java11 makes the problems. I changed to Java8 and it works. Thankyou for your help!
