### ISSUE TITLE
[BUG] Memory leak in 1.4.3.1 causing freezing at 99% memory

### ISSUE THREAD

**Issue by Dragonyichi** [Minecraft-Eternal/MC-Eternal-1.12#111]
**Describe the bug**
Memory starting at 60% but within 5 minutes going up to 99% and freezes the whole game. After about 5 seconds it unfreezes and memory goes to 90%, it climbs back up to 100% and freezes again all the time. Untill it just permafreezes/crashes at one point(freezing gets worse and worse). Also after a while I get massive FPS drops while in inventory (not in chests, just inventory) and whilst looking at yourself with F5. Also very laggy sometimes when looking at a certain player.

**Version of MC Eternal**
1.4.3.1

**To Reproduce**
After building a base(or spending time in the world) , it randomly starts happening at some point.

Didn't have this issue when playing 1.3.7
Also my gf is experiencing the same issue after a while, so does another friend.
It seems like something is leaking memory

**Comment by Ofthe6ix** [comment]
also having the same bug did some peeping around apperantly starting a new world was supposed to fix it but when i tried it did nothing for me

**Comment by criscky** [comment]
not enough information
- What was in your inventory, equipments and baubles?
- Can you send a log and a debug from WHEN it happens

Some simple things: 
- please use args or else your gb will go nuts
- please be sure you're not using any fish's undead equipament or have it in your inventory (this is pinned in the discord server)

**Comment by Ricket** [comment]
I found a memory leak from wearing a Chef's Toque: https://github.com/Electroblob77/Wizardry/issues/648

I also found some wasted memory (if playing on a server) from AncientWarfare2: https://github.com/P3pp3rF1y/AncientWarfare2/issues/1257

**Comment by SoggyCoffee** [comment]
Same issue, for me as well and friends become unplayable 

[debug_profile-results-2021-04-27_15.00.09.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6387061/debug_profile-results-2021-04-27_15.00.09.txt)

[logs_latest (1).log](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6387062/logs_latest.1.log)

**Comment by criscky** [comment]
since the person that open the issue didnt give the information that i requested, i'll assume that #145 and #146 will fix the issues
