### ISSUE TITLE
[BUG] Mob Spawning seems very low

### ISSUE THREAD

**Issue by Rechols77083** [Minecraft-Eternal/MC-Eternal-1.12#115]
Been playing the latest release, 1.4.3.1, in fact all the 1.4 versions and having a hard time just finding normal zombies, skeletons or Creepers.

Starting new games and would set time to night, and it took me about 30 mins to find my first creeper,  Just seems this version doesn't spawn the amount of normal Minecraft mobs, I see other mobs from other packs spawning, just seems very very light on zombies/skeletons/Creepers.   Just a note, went back to 1.3.7.1 and mobs seems to spawn fine :)

Not sure if this is by design, but it does seem odd that I can run out to pitch dark and not see any thing spawn, or when it becomes daylight, not to see any zombies start to catch fire etc

**Comment by cap1o** [comment]
I have noticed that for me too since i start to play at the new version of 1.4.3. 
I had a hard time to get loot from Reliquary and Enderman.
I hope this can be fix soon ^^.

**Comment by BrandtVanDenBerg** [comment]
#238 may fix this. We shall see.
