### ISSUE TITLE
[BUG] Erebus Dimension Crashing

### ISSUE THREAD

**Issue by MNRB-Zoro** [Minecraft-Eternal/MC-Eternal-1.12#116]
I'm playing on 1.3.7.1 and every time I try to descent on Erebus the the game crashes.
Is the issue resloved in the updated versions ?

**Comment by criscky** [comment]
disable waila, it`s a know bug in with the interaction between the 2 mods

**Comment by cornehoskam** [comment]
Will be fixed in the next version of MCE
