### ISSUE TITLE
[BUG] Minecraft Crashed Due to Unknown Sources

### ISSUE THREAD

**Issue by SlimGrim602** [Minecraft-Eternal/MC-Eternal-1.12#121]
**Describe the bug**
Whenever I opened the pack it just says the game crashed and gives me a link to the crash log (attached below)

**Version of MC Eternal**
1.4.3.1

**To Reproduce**
1. Launch the game
2. Game Crashes

**Expected behavior**
I expected the game to load properly.

**Screenshots**
![Screenshot 2021-04-23 161903](https://user-images.githubusercontent.com/60247246/115930880-d3ef9e80-a44f-11eb-85e3-8bd000965983.jpg)

**Additional context**
[crash-2021-04-23_16.17.31-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6368165/crash-2021-04-23_16.17.31-client.txt)
crash log

I am using the Sphax texture pack with the MC Eternal patch, the Sphax version is the 1.12 512x. I doubt it has anything to do with the error but it might idk.

**Comment by anabsolutesloth** [comment]
Allocate a lot more RAM to Minecraft or use a lower resolution resourcepack, 10GB with a 512x resourcepack and MCE will is far from sufficient, i would guess it will probably want atleast 6GB more.
Also, i believe keeping Crash issues to the discord is a good idea.
