### ISSUE TITLE
Ender dragon Broken?

### ISSUE THREAD

**Issue by aniket-patil-dev** [Minecraft-Eternal/MC-Eternal-1.12#122]
version 1.4.3.1 ender dragon regens its health even after all the ender crystals are destroyed 
its ok if its a new feature but the rate of regen is too high it took me two strength 2 potions but still the damage done was like 30% when the dragon was on the ground then its flies and is fully healed and power 5 bow is also useless against it

**Comment by cornehoskam** [comment]
The enderdragon spawns as a champion. Will be nerfed a bit in the next version.
