### ISSUE TITLE
[BUG] The crafting recipe for machine frame is not normal and extremely expensive

### ISSUE THREAD

**Issue by Murishinjuu** [Minecraft-Eternal/MC-Eternal-1.12#124]
**Describe the bug**
crafting recipe for machine frame (thermal expansion) is insanely hard 

**Version of MC Eternal**
1.4.3.1

**To Reproduce**
look at the crafting recipe

**Screenshots**
https://gyazo.com/da9cfe0bef895230328dd1ec7dc1a5d7

**Additional context**
for an early game mod i swear it was much simpler in the past

**Comment by criscky** [comment]
this is not a bug, it is intended
also thermal was buffed with more slots
![image](https://user-images.githubusercontent.com/5963821/116011515-d2fb7000-a5fb-11eb-97a7-c5387c089325.png)

**Comment by Murishinjuu** [comment]
oh didnt know about that my bad, but white phosphor seems super hard to get

**Comment by anabsolutesloth** [comment]
Currently, White Phosphor is impossible to get in the Curseforge release, due to an oversight with the Phosphorous Ore not spawning, the next patch will have things changed so that the machine frame can be obtained.
