### ISSUE TITLE
only half o f the people are having stutering issues on the server. 

### ISSUE THREAD

**Issue by kody395** [Minecraft-Eternal/MC-Eternal-1.12#125]
2 of us the game runs fine. 2 of us the game is basically unplayable. i know very little about computers but when i go to my task manager my cpu usage is at 20% but minecraft says everything is maxed at 100% and i have the most ram i can give it. im not really sure what to do as im not great with files or anything at all like this but im hoping someone can help us here. the problem only exists on this world/server and did not exist when we were on version 1.3.7

**Comment by cornehoskam** [comment]
You have not allocated enough resources to your game. Please join our discord server for personal support if you do not know how to allocate more resources.
