### ISSUE TITLE
lagging still

### ISSUE THREAD

**Issue by atari-lord** [Minecraft-Eternal/MC-Eternal-1.12#136]
Game is lagging, submitted a ticket a couple days ago and that was closed for some reason. After ten minutes the game just starts lagging. It lags for 5 seconds every 3 seconds. I exit the world and reload but lag is back immediately, even if I load a new world. If I close the game completely and relaunch the lag goes away, but always returns right around ten minutes into. I don't know how to look up args.
[latest.log](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6405678/latest.log)

MC Eternal 1.4.3.1

**Comment by cornehoskam** [comment]
Fill in the information as requested by @criscky on your previous issue.
