### ISSUE TITLE
Crashing when adding setting up environmental tech void ore miners

### ISSUE THREAD

**Issue by qooq8poop** [Minecraft-Eternal/MC-Eternal-1.12#137]
[crash-2021-04-30_11.24.16-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6406880/crash-2021-04-30_11.24.16-client.txt)

I added environmental tech to MC eternal. Whenever I set up a void ore miner, the game crashes. I can load the game just fine after and the void ore miners work. The initial message about the crash states that universal modifiers, environmental tech, valkyrie lib, and level-up are having the issue. This crash happens a few seconds after a void ore miner becomes operational and happens every time. I've attached the crash log.
I know this may be an issue for another board. If you know a better place to post my issue, please let me know.

**Comment by criscky** [comment]
if you added a mod and that mod is causing a issue with the pack, please remove the mod, and only make issue trackers about the modpack without modifications
i understand that you want that mod, but sometimes things just dont work
