### ISSUE TITLE
still lagging

### ISSUE THREAD

**Issue by atari-lord** [Minecraft-Eternal/MC-Eternal-1.12#140]
My issue keeps getting closed before I can get any assistance.
Still experiencing a major lag spikes. After ten minutes the game just starts lagging, even if I just stand idle. It lags for 5 seconds every 3 seconds. I do not have anything from fish's undead in my inventory. I exit the world and reload but lag is back immediately, even if I load a different world with an empty inventory. If I close the game completely and relaunch the lag goes away, but always returns right around ten minutes in. Allocated 10 gigs of ram, Java 1.8.0.51, no additional arguments.
![Screenshot (11)](https://user-images.githubusercontent.com/19884570/116950518-408a4a80-ac53-11eb-8ffb-4b87de34b25e.png)
[latest.log](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6418602/latest.log)

**Comment by criscky** [comment]
remove your hat and go to out discord and get the args that recommended to run the pack in the faq channel
this issue tracker is mainly for bugs in the modpack for support please go to discord where ppl can help more than in here
