### ISSUE TITLE
1.4.1 tree chop mod breaks Industrial foregoing plant gatherer tree farm

### ISSUE THREAD

**Issue by Dagarath915** [Minecraft-Eternal/MC-Eternal-1.12#17]
a basic 9x9 plant gatherer / plant sower tree farm using oak and spruce trees. The gatherer machine bugs out, gui won't open / trees won't harvest / machine loses it's upgrades when it's trying to take down trees. You can manually chop down trees and the machine gui will work until a new tree grows.  I removed ht tree chop mod on a restart and tree farm works normally.

**Comment by Dagarath915** [comment]
I was asked for some more detail.  I added the tree chop mod back to my game and checked the farm again.  The trees being harvested are following the tree chop mechanism, notching down the first block per pass.  When the trees break the drops all fall to the ground and aren't collected by the plant gatherer machine.  Taller trees leave wood / leaves high in the air that are not broken or retrieved by the plant gatherer. 

The tree chop mod is blocking or taking precedence over the tree take down mechanics of the plant gatherer, preventing it from gathering the materials and thus leaving all the items on the ground.   So far the GUI hasn't bugged out like the first report, but i'll let it run for awhile and recheck it.

**Comment by Dagarath915** [comment]
after letting the tree farm run a few hours while playing, the farm is stuck. the machine is no longer breaking trees at all (i.e. the tree chop way)  the machine has lost it's +4 range upgrade that was present earlier.

**Comment by anabsolutesloth** [comment]
Send this out to their Github: https://github.com/hammertater/treechop/issues
Hopefully they can implement a more thorough check to determine if the breaker of the tree is a player.
