### ISSUE TITLE
[BUG] Using Roots3 Radiance spell forces disconnect from server

### ISSUE THREAD

**Issue by richtoph3r** [Minecraft-Eternal/MC-Eternal-1.12#176]
**Describe the bug**
Using the Radiance spell from Roots3 forces client to disconnect from server in SP and MP

**Version of MC Eternal**
MC Eternal 1.12 1.4.3.1

**To Reproduce**
1. Equip Roots3 staff with Radiance spell infused into it
2. Use spell
3. Get booted from server with message "A fatal error has occurred, this connection is terminated"

**Expected behavior**
Spell shoots a beam of light that damages mobs

**Screenshots**

**Additional context**
Pastebin of errors between connection and force disconnect
https://pastebin.com/BzxKULn8

**Comment by criscky** [comment]
please update
valkirie skies seems the one causing that, and we removed that mod
