### ISSUE TITLE
[Problem] Open modular turrets not targeting certain mobs

### ISSUE THREAD

**Issue by lee3790** [Minecraft-Eternal/MC-Eternal-1.12#177]
**Describe the bug**
Turrets from open modular turrets do not target mobs from primitive mobs and vampirism. I found that the tags for mobs from these mods are different so I am wondering if you are willing to make changes to fix this.

**Version of MC Eternal**
1.3.7.1

**Comment by criscky** [comment]
it's not a problem in the pack we cannot fix
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/536
