### ISSUE TITLE
[BUG] Vanilla villages generating several thousand blocks away

### ISSUE THREAD

**Issue by VarianArdell** [Minecraft-Eternal/MC-Eternal-1.12#181]
**Describe the bug**
Vanilla villages spawning several thousand blocks away in either direction from spawn.

**Version of MC Eternal**
most recent version of MC Eternal as of this posting, which is 1.4.4

**To Reproduce**
1. install MC Eternal modpack
2. create new world
3. execute command "/locate Village"
4. cry as said command tells you the nearest village is located at (for most recent example) -23704, -14536 when your spawn point is at -140, 245

**Expected behavior**
villages spawning a lot closer than that

**Comment by VarianArdell** [comment]
if it's at all relevant, I have experienced this bug with both MultiMC and GDLauncher

**Comment by criscky** [comment]
i think that command will work only on vanilla, in modded we have a ton of others types of villages
so dont expect that command work in modded as well as it works in vanilla
i'm in a village and that **VANILLA** command wont work
