### ISSUE TITLE
[BUG] Advanced Rocketry Space Station not spawning

### ISSUE THREAD

**Issue by Pustekuchen98** [Minecraft-Eternal/MC-Eternal-1.12#192]
**Describe the bug**
Whenever i try to set up my Space Station and launch it to Space. It just doesnt spawn the Space Station in. If you ride with the rocket your only option after you land on air blocks (y=1000) is to launch the rocket again to go back to earth. You're not even able to leave the rocket.

**Version of MC Eternal**
1.3.7.1

**To Reproduce**
1. Build a Space Station
2. Save it
3. Put it in the Rocket with the Space Station ID Chip
4. Launch and get Stuck in an invisible rocket on air blocks without a space station generating and your only choice to fly back to earth by pressing space

**Expected behavior**
I expected that my prebuilt space station would generate and that i would land on it with my rocket

**Screenshots**
![2021-05-20_19 49 23](https://user-images.githubusercontent.com/7203120/119025822-cf61cb80-b9a4-11eb-824a-0d03ef127426.png)

**Additional context**
Server is NOT running Sponge. So it shouldn't be the sponge Issue that you find on google

**Comment by Pustekuchen98** [comment]
Why has the ticket been closed? Has it been fixed?

**Comment by anabsolutesloth** [comment]
> Why has the ticket been closed? Has it been fixed?

99% sure that it's just the issue where you can relog to fix it, if it is, i've not seen this variant.
maybe it's not, but idk, can't find the conversation on the discord that i swear did exist.
