### ISSUE TITLE
[BUG] Cannot craft any dimensional doors, world thread listed as item.null.name

### ISSUE THREAD

**Issue by richtoph3r** [Minecraft-Eternal/MC-Eternal-1.12#197]
**Describe the bug**
Attempting to craft any dimensional door results in server throwing "false" error in log and returning crafting ingredients to grid. World threads are listed in JEI and 

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Use any crafting table to assemble recipe
2a. Click to grab recipe output
3a. Output item refuses to be grabbed
2b. Shift-click to put item in inventory/hotbar
3b. Clicking to grab item in inventory returns it to the crafting table along with materials, as if never constructed
4b. Placing item in world results in half door being placed in world, with same result as 3b.

**Expected behavior**
Door is crafted, materials used, and item is able to be placed.

**Screenshots**

**Additional context**

I've uninstalled and reinstalled MC Eternal before creating the single player worlds.

What happens in a creative SP world
https://youtu.be/uusQh14U-Ks

What happens in Survival SP with cheats world
https://youtu.be/xf_bMfFHyuc

What happens on Survival MP server
https://youtu.be/jK8swRsxsGo

**Comment by criscky** [comment]
the false in the log is prob from immersive inteligence
in the server, please check dimensional doors config and see if this config is
`B:useEnderPearlsInCrafting=true`
or is
`B:useEnderPearlsInCrafting=false`

**Comment by richtoph3r** [comment]
> 
> 
> the false in the log is prob from immersive inteligence
> in the server, please check dimensional doors config and see if this config is
> `B:useEnderPearlsInCrafting=true`
> or is
> `B:useEnderPearlsInCrafting=false`

This was the fix, server (and server owner's) config was set to false while mine was set to true. This lead to the server owner being able to craft the doors while I was not. Much appreciated!
