### ISSUE TITLE
[BUG] Describe the bug in a single sentence

### ISSUE THREAD

**Issue by T3cube** [Minecraft-Eternal/MC-Eternal-1.12#200]
**Describe the bug**
making nuclearcraft infinite water source with water cells from tech reborn gives a load of empty cells

**Version of MC Eternal**
1.4.4

**To Reproduce**
when making nuclearcraft infinite water source, use stacked water cells instead. shiftclick

**Expected behavior**
return of the cell i used, not extra ones

this is also done in the ME crafting terminal

**Comment by criscky** [comment]
sorry about the late reply, but i think that's a bug in techreborn itself
i would suggest report that to them, but they just dont reply, i dont think we can fix that on our end

**Comment by T3cube** [comment]
i get free cells out of it i guess.
