### ISSUE TITLE
[BUG] Mobgriefing rule is ignored.

### ISSUE THREAD

**Issue by Tokeli** [Minecraft-Eternal/MC-Eternal-1.12#205]
**Describe the bug**
With mobgriefing set to false, vanilla creepers (and all the rest) still destroy blocks when exploding. Tested on SMP server.

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Do `/gamerule mobgriefing false`
2. Find a vanilla creeper and allow it to explode
3. Observe creeper creates a crater in the ground.

**Expected behavior**
Block destruction should be prevented with mobgriefing off.

**Comment by criscky** [comment]
i couldnt reproduce that error on my end, you didnt modified the pack in anyway by removing mods/adding mods/changing configs, right?

**Comment by anabsolutesloth** [comment]
The Gamerule command is Case Sensitive, you use mobGriefing, right?

**Comment by Tokeli** [comment]
I just now realized that it is, yeah, case sensitive. I could swear it didn't used to be, and it doesn't say anything about an invalid rule either. Sorry about that, no bug at all!
