### ISSUE TITLE
[BUG] Immersive Engineering Core Sample Drill doesn't give sample in End dimension.

### ISSUE THREAD

**Issue by Hamsterrhino** [Minecraft-Eternal/MC-Eternal-1.12#208]
**Describe the bug**
After working full cycle, CSD (core sample drill) doesn't give drill. Only makes a sound.

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Go to End
2. Put CSD and charge it (I use portable generator)
3. Use CSD and wait it to finish working.
4. In some cases it gives samples, in others just makes a sound

**Expected behavior**
Expected to give sample in every case

**Screenshots**
![image](https://user-images.githubusercontent.com/25804014/121819049-c0b0c080-cc93-11eb-9849-b7c1d8965b12.png)

**Comment by criscky** [comment]
i tried and i got the drill sample
i'm assuming you're using the pack and didnt modify the pack in anyway by changing configs or adding or removing mods, right?
![image](https://user-images.githubusercontent.com/5963821/122299393-4f138500-ced4-11eb-9f84-90d7f6d82907.png)

**Comment by Hamsterrhino** [comment]
And here lies a problem.
When there is nothing - drill gives sample.
When **i assume** there is something - drill doesn't give sample.

My only assumption being that game doesn't know how to draw endstone with tungsten in it.
And yes, i was using just modpack with no changes.

You just need to try 10 different chunks, at some point it won't give anything

**Comment by criscky** [comment]
i guess it doesnt have any?
i'm not sure if immersive actually adds stuff to the end, because we didnt modify anything in immersive's excavators

**Comment by Hamsterrhino** [comment]
I had to look up a few things.

Tungsten is added via tech reborn.
But you can get "mineral veins" in IE and use excavator on it.
But i guess use of mining drill just wasn't checked and it just doesn't work properly.

**Comment by Hamsterrhino** [comment]
![image](https://user-images.githubusercontent.com/25804014/122302716-2955a280-cf0b-11eb-8387-d31acb80305c.png)
Finally loaded game just to show
There is also tungsten from II (immersive intelligence), so my guess is that just wrong tungsten was used for mineral deposists.
![image](https://user-images.githubusercontent.com/25804014/122302833-530ec980-cf0b-11eb-82ed-8171cb0a54b7.png)
There is another mineral deposit
![image](https://user-images.githubusercontent.com/25804014/122302922-73d71f00-cf0b-11eb-9626-ecaaf52cd987.png)

And there is no deposit that uses II tungsten.

**Comment by Hamsterrhino** [comment]
And there is some problem with using dimensions from different mods.
![image](https://user-images.githubusercontent.com/25804014/122303246-e811c280-cf0b-11eb-9f2a-812d39521d02.png)
![image](https://user-images.githubusercontent.com/25804014/122303265-f4961b00-cf0b-11eb-9896-2997ce4cd873.png)

**Comment by anabsolutesloth** [comment]
The manual appears to state that it can be found anywhere _except_ The End, which is Dimension 1.
It's possible it's trying to create something there when you drill, but gets stuck because there either not enough Blocks below it, or simply does not know what to generate since there is nothing it can or should.
