### ISSUE TITLE
Game crashes on loading 

### ISSUE THREAD

**Issue by ghost** [Minecraft-Eternal/MC-Eternal-1.12#21]
The game crashes while loading the model manager. I'm on this version because I wanted to try out a server that I managed to get running (really easy to set up btw). Anyway it's a little annoying because all I get is:
An unexpected error occured.
Exit code -0

**Comment by RedPandasRule021** [comment]
The game crashes while loading the model manager. I'm on this version because I wanted to try out a server that I managed to get running (really easy to set up btw). Anyway it's a little annoying because all I get is:
An unexpected error occured.
Exit code -0

**Comment by criscky** [comment]
that's not enough information
what version?
what launcher?
some log please?

**Comment by ghost** [comment]
I don’t currently have access to my pc but I was using the curseforge launcher. I don’t know how the launcher works but I’ll try and get the release instead of the beta if I can when I get home.

**Comment by criscky** [comment]
i'm pretty sure it's a problem in your launcher (curse is know by it's problems) or you didnt allocated enough ram, please send a log

**Comment by ghost** [comment]
I will send a log as soon as I can. It might be a problem with the ram because the ram capped out at 3(something)65mb so I might try to allocate more when I get home.

**Comment by criscky** [comment]
yes, that's not enough, to run the pack you need at least 7~8 if you're using the beta, and please next time if it's not a bug in the pack try ask in the discord first
https://discord.gg/mceternal

**Comment by ghost** [comment]
Allocating more ram from 4gb to 7gb fixed my issue. Thank you for your help!
