### ISSUE TITLE
[BUG] MEkanism Machines using way too much Power

### ISSUE THREAD

**Issue by malevors** [Minecraft-Eternal/MC-Eternal-1.12#210]
**Describe the bug**
Some Mekanism Machines like the Metallurgic Infuser and its Factory Versions are using way too much energy. In this case the Infuser takes 1kRF instead of 20RF.

**Version of MC Eternal**
1.4.4

**Expected behavior**
I expected the same Energy consumation as the Mekanism Wiki is saying

**Comment by criscky** [comment]
that's not a problem
in the pack configs are changed
