### ISSUE TITLE
[BUG] Breaking Alveary Frame Holder destroys frame

### ISSUE THREAD

**Issue by Sakarmit** [Minecraft-Eternal/MC-Eternal-1.12#211]
**Describe the bug**
Breaking the Alveary Frame Holder with frame still inside doesn't drop the frame placed inside

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Place Alveary Frame Holder
2. Place any frame inside the Frame Holder
3. Break the Alveary Frame Holder
4. Alveary Frame Holder drops but frame inside doesn't

**Expected behavior:**
When the Alveary Frame Holder is broken it should also drop the frame placed inside it

**Comment by criscky** [comment]
that's a bug in career bees itself, since tema isnt modding anymore i dont think it will be fixed
