### ISSUE TITLE
[Suggestion] Use Rocky Tweaks and a custom script to make different Obsidian skulls useable in different recipes.

### ISSUE THREAD

**Issue by DanDragonWolf** [Minecraft-Eternal/MC-Eternal-1.12#212]
Today I released a custom script on Curseforge that lets any obsidian skull to be used in the Obsidian Shield and Obsidian Water Walking Boots recipes. I would like to have you use it in this modpack once my script gets approved. Here is a link (It might not let you see it until it gets approved): [https://www.curseforge.com/minecraft/customization/obsidian-skull-tweaks](https://www.curseforge.com/minecraft/customization/obsidian-skull-tweaks)

**Comment by criscky** [comment]
try post that in discord, i would like this issue tracker to be only for issues
