### ISSUE TITLE
[BUG] Describe the bug in a single sentence

### ISSUE THREAD

**Issue by starkillerone** [Minecraft-Eternal/MC-Eternal-1.12#213]
**Describe the bug**

**Version of MC Eternal**
1.4.4  (1.12.2)

**To Reproduce**
1. preload chunks
2. load world and dig down to find now ores

**Expected behavior**
see ore after going in two very deep caves

**Additional context**
most trees and all grass blocks are gone to in all biomes unknow if structures were effected to

**Comment by anabsolutesloth** [comment]
You need to set it to Full Gen in the Pregen UI.
As for Command pregeneration, i believe it should be full gen by default, if it's not, there should be a way to make it, check [their curseforge page](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator).
Also, for issues like this, please come to our Discord, it's linked on our Curseforge page, and also a message when you log into a world in the pack.
