### ISSUE TITLE
radiation boxes dont give loot

### ISSUE THREAD

**Issue by T3cube** [Minecraft-Eternal/MC-Eternal-1.12#218]
**Describe the bug**
when stack opening radiation boxes from the store or other means, you only get one box worth of items.

further, you dont even get items of you open the rest of the boxes manually, they are always blank after the first one.

**Version of MC Eternal**
1.4.4

**To Reproduce**
get a stack of the radiation boxes, and shiftclick to open them

**Expected behavior**
i should recieve items from all of them, not just one

**Comment by anabsolutesloth** [comment]
Intentional, you only get the contents when you do not already have them.
