### ISSUE TITLE
[BUG] Can't complete the "Netherumbrian Pipes" quest in the "Magic and Spellcasting" tab

### ISSUE THREAD

**Issue by MacNCheese3** [Minecraft-Eternal/MC-Eternal-1.12#219]
**Describe the bug**
There is no recipe for the netherumbrian pipes from totemic mod.

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Type in "Netherumbrian Pipes" in JEI searchbar.
2. Check both recipe and uses on it.
3. Realize there is no survival way to complete the quest or get the item
4. Cry in corner

**Expected behavior**
Too see it gatherable from a loot box.

**Screenshots**
<img width="350" alt="uses" src="https://user-images.githubusercontent.com/86283407/122872273-3b19ba00-d2fe-11eb-996f-956bce141273.png">
(Uses)
<img width="360" alt="pipes" src="https://user-images.githubusercontent.com/86283407/122872285-40770480-d2fe-11eb-944e-6f396a24cfc1.png">
(Recipes)

**Additional context**
None... besides nice broken stuff adam

**Comment by Handeril** [comment]
It is stated [here](https://ftb.fandom.com/wiki/Totemic) that the Netherumbrian Pipes are an "Unused item" in Totemic, I'll go out of my way to make a recipe script for it anyways, though.

Why, you might ask? I just feel like contributing another fix to the pack.

**Comment by Handeril** [comment]
![New Recipe](https://user-images.githubusercontent.com/83894721/127311469-6636546b-befe-4c00-bd25-bc694c2fe6db.png)

To achieve this, I made a script that I just simply named "Totemic Fix".

**Comment by Handeril** [comment]
I'm having a major n00b moment here - @criscky, can you help me add "Totemic Fix.zs" to the upcoming release?

Here's the code:

`#For MC-Eternal - Script by Handeril

print("Totemic Fix Is Now Loading!");

recipes.addShaped(<totemic:nether_pipe>, [[<ore:ingotGold>, null, <totemic:flute>], [<ore:ingotGold>, <ore:hideBuffalo>, <ore:ingotNetherite>], [<ore:ingotGold>, <ore:hideBuffalo>, null]]);

print("Totemic Fix Is Now Loaded! Netherumbrian Pipes are craftable now!");`

Hope this helped out, going to go work on other things now.

**Comment by criscky** [comment]
i dont even know if the item was properly implemented, i think the best would just be removing the item from the quest because if it bugs somehow there will be no fix, since it's not a "item that you would get normally"

**Comment by adam9899** [comment]
recipe looks good

> i dont even know if the item was properly implemented, i think the best would just be removing the item from the quest because if it bugs somehow there will be no fix, since it's not a "item that you would get normally"

the item used to be in the shop for a very long time, i removed it when i revamped the shop, not due to any issues

**Comment by Handeril** [comment]
@adam9899 Did you get my script from the Game Suggestions channel on the Discord? [Kind of inexperienced with how to contribute to the project through Git...]

**Comment by anabsolutesloth** [comment]
#308 has been merged, Resolving this, Closing.
