### ISSUE TITLE
[BUG] Molten Chestplate causes max ram usage and crash

### ISSUE THREAD

**Issue by Birdtalon** [Minecraft-Eternal/MC-Eternal-1.12#22]
**Describe the bug**
Wearing the molten chestplate causes ram to climb to 100% usage and crash the game.

**Version of MC Eternal**
1.4.1 beta

**To Reproduce**

1. Wear Molten Chestplate from Fish's Undead Rising
2. Idle for 5-10 minutes
3. Ram will rise to 100% usage.

**Expected behavior**
The game not to crash

**Comment by anabsolutesloth** [comment]
Report to Fish's Undead Rising author: https://github.com/FuGu0416/Fishs_Undead_Rising/issues

**Comment by cornehoskam** [comment]
Closed for the time being while the issue is outside of our reach
