### ISSUE TITLE
[BUG] 'Hole Filler - Light' despawns hostile mobs, crashes game

### ISSUE THREAD

**Issue by Xenthori** [Minecraft-Eternal/MC-Eternal-1.12#220]
**Describe the bug**
When using a "Hole Filler - Light" from Hole Filler Mod to light up a dark area in the overworld (I have not attempted to recreate in other dimensions), hostile mobs in the area of the effect will despawn once approached. Additionally, there is a high likelihood of game crashing when used, assumedly (but not confirmed) due to errors with a mob despawning. Even after rejoining the world, the game will crash after 1-5 seconds unless temporarily swapped to peaceful.

**Version of MC Eternal**
Minecraft Eternal Client 1.4.4

**To Reproduce**
1. Go to dark location (such as a cave) in overworld with hostile mobs at a distance, does not matter if vanilla or modded.
2. Right click the 'Hole Filler - Light' with torches in inventory to light up the darkened area, may require multiple attempts.
3. Approach mobs now in the light created by the Hole Filler.

**Expected behavior**
Expected behavior would be similar to placing down torches, lighting up the area but doing nothing to despawn mobs already there, instead only preventing future mob spawn due to light level.
 
**Screenshots**
![](https://i.gyazo.com/af16f35d107aaf21f2caac4918bfeccd.png)

**Additional context**
Crashes will continue to reoccur even after reloading into the world. The temporary solution I've found is to load world and immediately enter the pause menu, and swap to peaceful to despawn all hostile mobs. This is not a viable long-term solution as it has the possibility of despawning rare boss monsters players may be interested in keeping around.

[crash-2021-06-22_17.18.24-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6697743/crash-2021-06-22_17.18.24-client.txt)
[crash-2021-06-22_17.12.32-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6697744/crash-2021-06-22_17.12.32-client.txt)
[crash-2021-06-22_17.03.34-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6697746/crash-2021-06-22_17.03.34-client.txt)
[crash-2021-06-22_17.22.22-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6697747/crash-2021-06-22_17.22.22-client.txt)

**Comment by criscky** [comment]
i couldnt recreate this, but it frooze for a second while calculating, but it didnt crash
also i'm using a more recent java than you, yours is 6 years old, try update and see if the crash still happens, it could just be because your java is too old
can you try update your java?

**Comment by Xenthori** [comment]
> i couldnt recreate this, but it frooze for a second while calculating, but it didnt crash
> also i'm using a more recent java than you, yours is 6 years old, try update and see if the crash still happens, it could just be because your java is too old
> can you try update your java?

doing so now, will post results after updating and trying to recreate again

**Comment by Xenthori** [comment]
After testing a good deal, the number of crashes have gone down significantly and I don't believe them to be related to the Light Orb anymore, but the despawning of mobs continue to persist - I do not know if this is intentional interaction or not, but feels odd in a more difficult modpack for a very easily obtainable item. If this is the intended use for Light Orbs, i'll close the issue.

**Comment by Xenthori** [comment]
https://user-images.githubusercontent.com/86328460/123192166-f873f100-d467-11eb-8963-4305a1d2f6c3.mp4

did get a short video of the mobs despawning after approaching

**Comment by criscky** [comment]
ok, unfortunately i think we cannot fix it in our end, since there's no configs about the light one, the max we can do is disable the recipe for that item
i would recommend you report to the Hole Filler mod, but i'm not sure if you'll be able to, because that mod doesnt even have a issue tracker

**Comment by Xenthori** [comment]
understood, thank you for the assistance regardless
