### ISSUE TITLE
[BUG] Eating cooked carrots gives you bowls

### ISSUE THREAD

**Issue by slamanander** [Minecraft-Eternal/MC-Eternal-1.12#225]
**Describe the bug**
When eating cooked carrots from Mystical World a bowl will appear in your inventory.

**Version of MC Eternal**
1.4.4 (Singleplayer)

**To Reproduce**
1. Cook carrots in a furnace
2. Eat them
3. See error

**Expected behavior**
Bowls not appearing

**Screenshots**
N/A

**Comment by anabsolutesloth** [comment]
Forward to Mystical World's github, as they're still doing 1.12 bugfixes: https://github.com/MysticMods/MysticalWorld/issues

**Comment by criscky** [comment]
fixed by #221
