### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by Gidgitz** [Minecraft-Eternal/MC-Eternal-1.12#228]
Not all to much to describe. Completed a quest and got 3 of these as a reward out of a common chest. 
[
![2021-06-28_02 13 19](https://user-images.githubusercontent.com/86589512/123589355-15d1f380-d7b7-11eb-834d-22e0681f1dee.png)
](url)

**Comment by anabsolutesloth** [comment]
Addressed in #226

**Comment by Gidgitz** [comment]
Thank you for the quick reply. I will close this out. I appreciate you guys
