### ISSUE TITLE
[BUG] Industrial Centrifuge deuterium cell crafting recipe not working correctly.

### ISSUE THREAD

**Issue by ghost** [Minecraft-Eternal/MC-Eternal-1.12#23]
Describe the bug
When inserting hydrogen cells into a Tech Reborn Industrial Centrifuge, one deuterium cell and 3 empty cells are expected, but it instead outputs tin, copper and electrum ingots as well as tungsten dust. 

Version of MC Eternal
1.4.1

To Reproduce
Put hydrogen cells into an industrial centrifuge. 

Expected behavior
4 Hydrogen cells are supposed to craft 1 deuterium cell and 3 empty cells

![hydrogen](https://user-images.githubusercontent.com/80983084/111832307-e88cc400-88f0-11eb-8bf8-0725b1b04ebc.png)

![image](https://user-images.githubusercontent.com/80983084/111833484-87fe8680-88f2-11eb-8b04-947e5b5d856e.png)

**Comment by criscky** [comment]
thanks for your report, that's a bug in the newer version of tech reborn with reborn core, somehow they're not reading the NBT data, a pull was made to downgrade the version

**Comment by cornehoskam** [comment]
Fixed & closed until further notice :)
