### ISSUE TITLE
A parasite from Fish's Undead Rising is attached to me but is completely invincible

### ISSUE THREAD

**Issue by SizzleWizzle** [Minecraft-Eternal/MC-Eternal-1.12#230]
**Describe the bug**
The parasite is stuck to me every time I log in, or go to a different dimension. I can't kill it, or other enemies. Interaction with blocks (breaking, placing, opening, etc) doesn't work either. I've tried killing myself, and getting other parasites stuck on me, but the result is the glitched enemy floating in the air. It comes back after a while though, and I have permanent hunger.

**Version of MC Eternal**
I believe it is 1.3.7.1 (the 1.12 release on curseforge)

**To Reproduce**
No idea, it just happened one day. I remember killing a bunch of parasites, and then eventually I went to the nether. It appeared out of no where and I couldn't do anything about it.

**Screenshots**
![2021-06-29_19 08 53](https://user-images.githubusercontent.com/86636005/123883079-cb16bf80-d90d-11eb-98c5-4e02d0eee92c.png)

**Additional context**
If you left click on the parasite, it pops off and floats like I described at the top of the report. I found a reddit post about someone having the same issue, but have found no solution that works.

**Comment by anabsolutesloth** [comment]
Please go to the discord.

**Comment by SizzleWizzle** [comment]
What is the discord
