### ISSUE TITLE
Invincible Parasite stuck to me every time I log on, floats in the air when I left click, permanent hunger debuff

### ISSUE THREAD

**Issue by SizzleWizzle** [Minecraft-Eternal/MC-Eternal-1.12#235]
Describe the bug
The parasite is stuck to me every time I log in, or go to a different dimension. I can't kill it, or other enemies. Interaction with blocks (breaking, placing, opening, etc) doesn't work either. I've tried killing myself, and getting other parasites stuck on me, but the result is the glitched enemy floating in the air. It comes back after a while though, and I have permanent hunger.

Version of MC Eternal
I believe it is 1.3.7.1 (the 1.12 release on curseforge)

To Reproduce
No idea, it just happened one day. I remember killing a bunch of parasites, and then eventually I went to the nether. It appeared out of no where and I couldn't do anything about it.

![2021-06-29_19 08 53](https://user-images.githubusercontent.com/86636005/124020487-f520be00-d9af-11eb-9f25-c32292320d90.png)

Additional context
If you left click on the parasite, it pops off and floats like I described at the top of the report. I found a reddit post about someone having the same issue, but have found no solution that works.

**Comment by criscky** [comment]
#230
as said before, go to discord, the link is in the curseforge page and in the main menu of the game, and if you're in the latest version everytime you join the link will showup
this issue tracker is for bug that we can fix, for player support please go to discord that we can give better support
