### ISSUE TITLE
All 1.4 versions use over 10 GB of RAM in Singleplayer

### ISSUE THREAD

**Issue by DavidLXXV** [Minecraft-Eternal/MC-Eternal-1.12#245]
During the load screen and the actual game MC Eternal uses at least 8 GB of RAM over surpassing 10 GB - I have not seen this issue anywhere else online so was wondering if there was an easy fix. This is not on a server just my own client in singleplayer.

This occurs on all versions above 1.4.0

This occurs whenever I am in game, in a menu or loading the game. I do not know how to reproduce this issue but it happens every time without fail to me.

**Comment by criscky** [comment]
not a issue for git, go to discord to get support
