### ISSUE TITLE
[BUG] When opening a single player world, the game crashes.

### ISSUE THREAD

**Issue by xNiqht** [Minecraft-Eternal/MC-Eternal-1.12#267]
**Describe the bug**
When opening a single player world, the game crashes.

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. go into curseforge
2. Click on play mceternal
3. when in mceternal, open a single player world

**Expected behavior**
I expected my single player world to open.

**Screenshots**

![Screenshot (117)](https://user-images.githubusercontent.com/87232268/125163712-67399580-e15c-11eb-9788-c27beb7faef9.png)

**Additional context**
I tried allocating 11g of ram to mceternal, and 8g neither work same problem with both. Just saying this if it helps.

**Comment by criscky** [comment]
not a issue for git, go to discord to get support
