### ISSUE TITLE
when i try to start up mc eternal a message pops up saying that "these following mod(s) have been identified as possible issues: tinkers construct and FoamFix"

### ISSUE THREAD

**Issue by GustoGuy** [Minecraft-Eternal/MC-Eternal-1.12#280]
**Describe the bug**
like i said, when i start minecraft a message pops up saying that two mods are identified as potential causes, to be exact the message said "An error during startup prevented minecraft from being started"
**Version of MC Eternal**
Which version of the mod pack are you on?
1.12.2

**To Reproduce**
1. Go to 'curse forge'
2. Click on 'install, then when its done click play'
3. Scroll down to 'you dont scroll, the message just pops up after some loading'

**Expected behavior**
i expected the loading to finish and then the minecraft front page to show up, lol

**Screenshots**

**Additional context**
when i tried to click the "get link" button, it said it failed so that why im doing it here

**Comment by criscky** [comment]
go to discord to get support, this issue tracker is only for issues in the pack, that's a user issue
