### ISSUE TITLE
Packmode setting do nothing. Packmode recipes are disabled.

### ISSUE THREAD

**Issue by AshnakAGQ** [Minecraft-Eternal/MC-Eternal-1.12#282]
**Describe the bug**
I noticed I was able to craft the Aurorean Portal and Gaean Keystone even though they are supposed to be disabled. Switching packmodes does nothing. 

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Go to 'settings'
2. Click on 'packmode'
3. Change packmode
4. Restart
5. No changes

**Expected behavior**
Changing packmode should get the old recipes back.

**Additional context**
I noticed that files like AdvRocketry.zs were trying to use the packmode "normal" while the only packmode options in packmode.cfg are "Normal,(modern eternal)" and "Classic,(simple recipes)". The packmode mod requires these to be the same, otherwise it just disables these recipes.

There is a [fix ](https://discord.com/channels/640591918752858122/655443172385882131/856427632345874442) on the discord FAQ, but it has to be installed on both client and server, forcing everyone to manually download apply the fix. Please update the source code with this fix. The progression is broken with default recipes.

**Comment by criscky** [comment]
already fixed in dev
