### ISSUE TITLE
Cant progress through electroblobs wizardry 

### ISSUE THREAD

**Issue by Lynicry** [Minecraft-Eternal/MC-Eternal-1.12#283]
im playing on mc eternal. before i got started with the mod i waws discovering and doing things for it and was unlocking stuff in the book. Now when i open the book and do things, its stuck on the first page and i cant progress through the mod without knowing anything. any fix?

**Comment by criscky** [comment]
better ask in electroblob's git or discord
or even in our own discord (the mce one)
this git is only for modpack issues, that seems a mod issue
