### ISSUE TITLE
[BUG] Aurorian, Atum, Erebus spawns incorrectly.

### ISSUE THREAD

**Issue by mlystdcall** [Minecraft-Eternal/MC-Eternal-1.12#293]
**Describe the bug**
Aurorian, Atum, Erebus spawns incorrectly. They are almost the same as overworld rather than what they should be. Mobs, ores and terrains are the same as overworld and Twilight Forest. The aurorian does not spawn Cerulean Ore. Dungeon Locator always points to a place without the corresponding dungeon.

**Version of MC Eternal**
1.4.4

**To Reproduce**
1. Create a new world
2. Go to these dimensions either by rocket or by portal
3. See error

**Expected behavior**
They should spawn just like we only use the corresponding mods.

**Screenshots**
![2021-07-23_01 50 15](https://user-images.githubusercontent.com/53339363/126762482-01f29e6a-a927-4436-a74b-8d036cc85ace.png)

**Additional context**
I don't know whether this is intented to do. But however I could not get Cerulean Ore and other resources.
Classic packmode and modern packmode does not affect this bug.

**Comment by mlystdcall** [comment]
By the way, the waystones of these 3 dimensions always lost their infomation after I restarting the game. I have to reactivate the waystone every time.

**Comment by criscky** [comment]
was already fixed by #276
