### ISSUE TITLE
[BUG] Crash when coming from nether to overworld

### ISSUE THREAD

**Issue by Ghostly-Boi** [Minecraft-Eternal/MC-Eternal-1.12#296]
**Describe the bug**
The game crashed when I died on the nether and respawned in the overworld

**Version of MC Eternal**
1.5 beta

**To Reproduce**
1. Go to Nether
2. Die
3. Respawn in the overworld
4. Crash

**Expected behavior**
To just respawn normally

**Screenshots**

**Additional context**

**Comment by criscky** [comment]
can you send the crash report?

**Comment by criscky** [comment]
no reply, and i cannot reproduce and nobody else reported a similar crash
