### ISSUE TITLE
Issue between JEI and Betweenlands

### ISSUE THREAD

**Issue by SamohAwesome** [Minecraft-Eternal/MC-Eternal-1.12#303]
When I attempt to load the game it goes fine until i get to 6 out of 7 JEI loading recipes. Then it gets most of the way done and fails. The crash report says that it was cause by a JEI and the betweenlands

Im on 1.4.4 of mc eternals if that helps
<img width="1440" alt="Screen Shot 2021-07-29 at 6 58 03 PM" src="https://user-images.githubusercontent.com/72154565/127575909-dcc2dad8-cebb-476d-88eb-05e779713f5e.png">

**Comment by criscky** [comment]
that's most likely a ram issue, the pack needs at last 8gb allocated, for more Player Support go to discord, this issue tracker is only for pack issues, like a bad mod interaction
