### ISSUE TITLE
[BUG] Cyclic Sack of Holding drops an additional YABBA Barrel when used to pick one up

### ISSUE THREAD

**Issue by TooChexy** [Minecraft-Eternal/MC-Eternal-1.12#305]
**Describe the bug**
Cyclic Sack of Holding duplicates Barrels from YABBA 

**Version of MC Eternal**
1.4.4

1. Use Sack of Holding on Barrel from YABBA 
2. Barrel will be in Sack of Holding but also one on the ground

**Expected behavior**
Barrel is in the Sack of Holding

**Additional context**
The dropped Barrel is an empty barrel with the upgrades of the original Barrel

**Comment by anabsolutesloth** [comment]
It doesn't appear to duplicate Barrel upgrades, but it does duplicate the barrel.

**Comment by cornehoskam** [comment]
Thank you for the report, this issue has been fixed for the next version
