### ISSUE TITLE
[BUG] Game crashes, when entering a world

### ISSUE THREAD

**Issue by KarliCarlos** [Minecraft-Eternal/MC-Eternal-1.12#306]
Everytime when I try to enter a Server or a Singleplayer World I get an error report

Version: MC Eternal 1.4.4

To Reproduce: Go into a Mulitplayer or a Singleplayer world

Expected behavior: The game will send you a report and none of the Links work.

![IMG_0901](https://user-images.githubusercontent.com/88288166/127782144-bdf0c7fd-7db4-4b2d-96d3-f180557973db.JPEG)

Additional context: Two days ago it worked; My friend has the same problem

**Comment by criscky** [comment]
please go to discord and provide the crashreport in there
