### ISSUE TITLE
[BUG] Same loot pattern in all battle towers

### ISSUE THREAD

**Issue by QHarek** [Minecraft-Eternal/MC-Eternal-1.12#307]
**Describe the bug**
Same loot in all battle towers (same loot pattern, only the number is different)

**Version of MC Eternal**
1.5-RC

1st fl: rat traps and hotdogs
2nd fl: coal, vampire clock and iron
3rd fl: jack-o-lantern, steelleaf, arrow with rat
4th fl: blood infused iron ingot, nether stew
...

**Comment by anabsolutesloth** [comment]
There's not that many entries in it, so it's likely just poor luck, unless everything is organized in the same way, which would be weird, but it's more likely than not a Battletowers issue.

**Comment by QHarek** [comment]
> There's not that many entries in it, so it's likely just poor luck, unless everything is organized in the same way, which would be weird, but it's more likely than not a Battletowers issue.

Oh, ok, thanks!
