### ISSUE TITLE
IDK whats going on please help??

### ISSUE THREAD

**Issue by animelover090397** [Minecraft-Eternal/MC-Eternal-1.12#312]
So IDK if something needs to be updated or what but I downloaded whatever is the recent update for the mod and this is what pops up and I can't open the link because it says fail?? so idk what to do please help 
![Screenshot (245)](https://user-images.githubusercontent.com/59386670/127806398-03684a86-64ab-4ffa-8287-0d8d7d64c49e.png)
![Screenshot (246)](https://user-images.githubusercontent.com/59386670/127806417-4c6455f0-196c-432d-9476-7e80ad5e9a67.png)

**Comment by animelover090397** [comment]
PS i don't have those tabs open on the bottom so ignore that

**Comment by anabsolutesloth** [comment]
Please go to the Discord for crashes https://discord.gg/ZS6FRR3
Ping me in the client-questions-and-issues channel when you get there, and i'll help (almost) right away.

**Comment by animelover090397** [comment]
how do I get ahold of you?
![Screenshot (248)](https://user-images.githubusercontent.com/59386670/128095527-78067560-5af9-4567-b535-ce6f084b02cb.png)

now it shows this and i think I know what it is but it will not give me the link still
