### ISSUE TITLE
[BUG] Farming For Blockheads market is empty in 1.5-RC

### ISSUE THREAD

**Issue by BitVector** [Minecraft-Eternal/MC-Eternal-1.12#315]
**Describe the bug**
The market in the mod Farming For Blockheads contains zero entries. Inside of Market.json, "custom entries" has a missing comma after the "examplemod" entry, which is causing the market to be empty.

From instances\MCE_Client-1.5-RC\minecraft\config\FarmingForBlockheads\Market.json:
`"custom entries": {`
`    "__comment": "You can define additional items to be sold by the Market here. Defaults can be overridden. Prefix with ! to blacklist instead.",`
`    "examplemod:example_item": "2*minecraft:emerald"` **⬅️ MISSING COMMA HERE**
`    "harvestcraft:juniperberryseeditem": "1*minecraft:emerald"`
`}`

More info from here: https://github.com/blay09/FarmingForBlockheads/issues/82

**Version of MC Eternal**
1.5-RC version that was downloaded from Announcements channel on Discord.

**Comment by anabsolutesloth** [comment]
Oop i guess i forgot that when i copy-pasted it to make a PR.

**Comment by anabsolutesloth** [comment]
#316 fixed this, closing.
