### ISSUE TITLE
[BUG] Compact Machines 3 Preview Display Error

### ISSUE THREAD

**Issue by raydenhui** [Minecraft-Eternal/MC-Eternal-1.12#318]
**Describe the bug**
It should not display trapdoor. It should display compact machine wall.

**Version of MC Eternal**
1.5RC

**To Reproduce**
Click on the compact machine after use

**Screenshots**
![2021-08-06_17 13 46](https://user-images.githubusercontent.com/60210719/128489213-da843331-bcb1-4756-a35d-294e4ee924eb.png)

**Comment by criscky** [comment]
Send a debug.log and the latest.log
put it in https://gist.github.com/

**Comment by anabsolutesloth** [comment]
I think this is some bug with NEID, cause maybe CM doesn't expect IDs over 4096, unsure, could be totally different.

**Comment by criscky** [comment]
yea, it happens at random times i guess, but i never actually got it myself in a dev env, so wanted to check the log or debug

**Comment by criscky** [comment]
i'll close since there was no follow
