### ISSUE TITLE
[BUG] Harvester (@cyclic) doesnt affect crops | MCE 1.5-RC

### ISSUE THREAD

**Issue by QHarek** [Minecraft-Eternal/MC-Eternal-1.12#324]
I placed harvester from Cyclic with creative energy cube near it, in its AOE i placed on farmland and fertilized dirt 4 types of seeds:
1. wheat seed
2. wheat seed on crops
3. inferium seed
4. inferium seed on crops

And harverster harvests 1 and 3 nice, but it doesnt affect 2 and 4.

Version of MC Eternal
1.5-RC

![image](https://user-images.githubusercontent.com/63823726/129452036-b398c66b-e26f-4f9b-9126-db37ecd6061a.png)
![image](https://user-images.githubusercontent.com/63823726/129452047-05ca321c-3bf6-4cf5-a8b4-cdf256eebf07.png)

**Comment by anabsolutesloth** [comment]
Pretty sure we can't fix this, blame Cyclic for being bad >:V

**Comment by QHarek** [comment]
But in earlier versions it worked
