### ISSUE TITLE
[BUG] My singleplayer world repeatedly crashes upon reaching "Loading..." stage

### ISSUE THREAD

**Issue by Coolness01** [Minecraft-Eternal/MC-Eternal-1.12#331]
**Describe the bug**
Every time I join my specific singleplayer world, the game crashes. I have uninstalled and reinstalled the modpack to try to fix an fps issue, while copying my world folder from the previous version (before I uninstalled the modpack) and pasting it into my saves folder.

**Version of MC Eternal**
I am currently using MC Eternal v. 1.4.4

**To Reproduce**
1. Open Launcher
2. Launch MC Eternal
3. Open specific world
4. Game Crashes
**Expected behavior**
I expected to be able to join my singleplayer world without any problems.

**Screenshots**

**Additional context**
There have been issues with LittleTiles on this world
I have gotten incredibly far in the world, so I cannot muster the will to start over.

**Comment by criscky** [comment]
i see no crash, and no way to actually reproduce
please head to discord to get help with that
