### ISSUE TITLE
[BUG] Can't download latest version of pack.

### ISSUE THREAD

**Issue by YKtut** [Minecraft-Eternal/MC-Eternal-1.12#332]
Which version of the mod pack are you on?
I am trying to download the latest version of the pack but while I install it gives me the error that it is missing child addon 229703. 

**To Reproduce**
1. Go to main pack site
2. Click on install
3. See error

**Expected behavior**
To see a red flag saying 

**Screenshots**
![image_2021-08-16_193639](https://user-images.githubusercontent.com/89050142/129641991-02188d0d-20c0-4e59-8f7c-a48c86e3181c.png)

**Comment by dweinert** [comment]
Me and multiple people are getting the same error and can't download the mod from curseforge. It seems to be the 28th mod during the install.

edit:
Use GDlauncher as a current workarround.

**Comment by YKtut** [comment]
Bet ok

**Comment by criscky** [comment]
curse is broken
