### ISSUE TITLE
The GUI scale is abnormal in other languages

### ISSUE THREAD

**Issue by FruityMaxine** [Minecraft-Eternal/MC-Eternal-1.12#338]
**Describe the bug**
When switching to simplified or traditional Chinese, the GUI scale automatically becomes smaller and cannot be adjusted. It can be restored when switching to English

**Version of MC Eternal**
1.4.4
**To Reproduce**
1. Go to 'languages'
2. Click on 'Chinese(At the end of the list)'
3. Go to 'Options' then 'video settings' then 'GUI scale:Auto'
4. See error:GUI way too small

**Expected behavior**
GUI can be displayed normally in Chinese

**Screenshots**
![屏幕截图(1)](https://user-images.githubusercontent.com/89344622/130356527-c495cd0a-551f-4787-87c1-baf2628c4324.png)

**Comment by FruityMaxine** [comment]
I understand that the author may be busy, but if the bug cannot be fixed in time, the update of the integration package will be meaningless

**Comment by criscky** [comment]
sorry, i dont think we can solve that issue it could one mod, or two, or three interacting and bugging, if you can find what mod you should report to the author of that mod
we'll might check, but that would mean just remove all the mods and adding one by one to see which one bugout
but in the meantime can you just play in english?

**Comment by raydenhui** [comment]
This is the bug of Minecraft, not the modpack.
