### ISSUE TITLE
Resource pack folder not found

### ISSUE THREAD

**Issue by gam3rl1ves** [Minecraft-Eternal/MC-Eternal-1.12#340]
![dsfdsfgsde](https://user-images.githubusercontent.com/89367261/130380048-25c8bbc3-f107-4861-8c08-f8a453f503ff.PNG)
![fsdfsdfs](https://user-images.githubusercontent.com/89367261/130380055-6db4c896-7b23-4957-95ce-783af823942e.PNG)
i am trying to load optifine into it and when i click the link in the game for resource packs folder it says it cannot be found. but there is a folder for it in the minecraft folder

**Comment by anabsolutesloth** [comment]
Pretty sure this is either a Minecraft problem or a Curseforge problem, so we can't really fix it, quite sure it happens in other packs aswell.
Go to our discord for stuff like this please.
