### ISSUE TITLE
1.4.4 not released but curseforge does?

### ISSUE THREAD

**Issue by Darkentik** [Minecraft-Eternal/MC-Eternal-1.12#342]
Hey,
i ´m writing a bash script for provisioning a mc eternal server from scratch and struggle with collecting a link for downloading the server pack.
Now i´m confused because here on curseforge they give you a 1.4.4 version for download:
https://www.curseforge.com/minecraft/modpacks/minecraft-eternal/files/3305937
but here in the github repo the 1.4.4 is still in BETA?

Did i miss something?

Thanks a lot.

**Comment by criscky** [comment]
use curse, not all betas are released in git, if you have a question ask in discord, this git is only for bugs in the pack

**Comment by anabsolutesloth** [comment]
> but here in the github repo the 1.4.4 is still in BETA?

1.4.4 is not in Beta, but it is of course being used as a base for the next update, 1.5, 1.4.4 is proper Release, even if slightly broken.
