### ISSUE TITLE
gamerule doDaylightCycle to false, doesn't stop the sun/moon moving and advancing time

### ISSUE THREAD

**Issue by Hokage3211** [Minecraft-Eternal/MC-Eternal-1.12#343]
I was trying to pause the time to set up the server, and I noticed it eventually became night even though I had set the gamerule to false, which normally stops time. 

It's a very minor bug, but a bug nonetheless.

**Comment by anabsolutesloth** [comment]
Gamerules are Case-sensitive, in this instance, it should be `doDaylightCycle` are you sure you had it correct?

**Comment by Hokage3211** [comment]
actually you're right I may have gotten the casing wrong, it seems to be frozen now. Sorry for that!
