### ISSUE TITLE
[BUG] Summoner can spawn in the overworld

### ISSUE THREAD

**Issue by AerieAngel** [Minecraft-Eternal/MC-Eternal-1.12#371]
### Description of the Bug

Not much to say other than the title, no idea how it spawned in the overworld I was just walking around and it was there

### Expected Behaviour

Summoner shouldn't spawn in the overworld

### Modpack Version

1.4.4

**Comment by anabsolutesloth** [comment]
Can you like give more info? such as where it was found, your Multimob/Summoner config files from your install, etc?

**Comment by criscky** [comment]
not really a bug, ancient warfare have structures that spawn them

**Comment by criscky** [comment]
i'll close this, if you have any more questions, re-open
