### ISSUE TITLE
[BUG] Possible Cloud Pet Loophole

### ISSUE THREAD

**Issue by IcewaveGaming** [Minecraft-Eternal/MC-Eternal-1.12#377]
### Description of the Bug

The April Fools pet is enabled, so if you activate it on April 1st you can get a cloud pet and achieve early creative flight. The April Fools pet spawns in three Microsoft CEOs: Bill Gates, Steve Ballmer, and Satya Nadella. By starting the trade line, you can get a cloud pet easily and achieve early creative flight without an angel ring. The flight works even if the pet is disabled.

### Expected Behaviour

1. Activate April Fools pet on April 1st
2. April Fools pet disabled

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
this is ancient, but cloud pet flight does not appear to work if it is disabled from my observations.
