### ISSUE TITLE
[BUG] Lag'b'gon doesn't seem to clear entities/items correctly

### ISSUE THREAD

**Issue by SonicEdge** [Minecraft-Eternal/MC-Eternal-1.12#380]
### Description of the Bug

When Lagbgon removes entities and items, it actually leaves behind almost all mobs and items.
Furthermore, blacklisting entities from being cleared using the in-game /bgon toggleentitiy command doesn't seem to actually blacklist that mob from being cleared, according to other players on my server.

### Expected Behaviour

Lag'b'gone should clear all items and entities, aside from blacklisted items/entities.

### Modpack Version

1.5

### Extra Info

I didn't have these issues when I'd added the mod myself in 1.4.4

**Comment by criscky** [comment]
read my pinned message in discord, that is know, and not a MCE problem
