### ISSUE TITLE
[BUG] Attempting to craft an IE Reinforced Storage Crate results in wrong item.

### ISSUE THREAD

**Issue by thotbegone** [Minecraft-Eternal/MC-Eternal-1.12#387]
### Description of the Bug

Crafting a 'Reinforced Storage Crate' from Immersive Engineering results in a 'Small Storage Crate (Box)', making it impossible to create certain multiblocks.

### Expected Behaviour

Crafting should result in a Reinforced Storage Crate, not a Small Storage Crate.

### Modpack Version

1.5

### Screenshots

![crate](https://user-images.githubusercontent.com/37526284/134797590-636ff158-6e4c-490d-bcfc-bfde1c5992ab.png)

**Comment by anabsolutesloth** [comment]
Bug in Immersive Intelligence, will be solved if and when we update the mod.
#blameadam for adding ImmInt in an indev state :V

**Comment by anabsolutesloth** [comment]
was fixed in 1.6, but immintel is gone in 1.6.1 so this extra fixed now
