### ISSUE TITLE
Using server this error occurs

### ISSUE THREAD

**Issue by HxHL** [Minecraft-Eternal/MC-Eternal-1.12#388]
[FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.

Any help 
Full crash report: https://pastebin.pl/view/5fc40efc

**Comment by anabsolutesloth** [comment]
Gottschcore needs Forge 14.23.5.2854 to run, also update to MCE 1.5.
