### ISSUE TITLE
Quest's On Server's Don't Work

### ISSUE THREAD

**Issue by ezooopolis222** [Minecraft-Eternal/MC-Eternal-1.12#389]
### Description of the Bug

When i join a server that i am hosting the game doesn't spawn me with the items it does in singleplayer, and when i try to spawn in the quest book from FTBQuests it says the item doesn't exist. I don't know what i am doing wrong or what it happening but it's annoying

### Expected Behaviour

Spawn with Book
Try to spawn in book, it's supposed to give you the book
Quests are supposed to work

### Modpack Version

14.23.5.2847

**Comment by anabsolutesloth** [comment]
You ran the vanilla server jar, that just boots vanilla, use the Launch script provided in the server files.
You will likely have to add an -Xmx arg to the launch script manually because @cornehoskam is a silly guy :V
