### ISSUE TITLE
Banned from discord falsly

### ISSUE THREAD

**Issue by TheRealRitzer** [Minecraft-Eternal/MC-Eternal-1.12#391]
### Description of the Bug

Not a bug, but i was banned from your discord, natsu dragneel, because of something my dad said, says i was banned for being antivax which im clearly not considering not once did me or my dad say we dont think the vaccine should be taken, so if i could be unbanned that would be awesome

### Expected Behaviour

not a bug

### Modpack Version

1

**Comment by anabsolutesloth** [comment]
Please don't post this here, contact Goat#3045 on discord instead.

**Comment by OveR1337XD** [comment]
LOL
