### ISSUE TITLE
TreeChop and FutureMC sweet berry bush IllegalArgumentException, 1.4.2 Beta

### ISSUE THREAD

**Issue by incomingnerd** [Minecraft-Eternal/MC-Eternal-1.12#40]
**Describe the bug**
TreeChop mod causes an IllegalArgumentException and crash to title screen when a tree is in contact with a FutureMC sweet berry bush.

**Version of MC Eternal**
1.4.2 Beta

**To Reproduce**
1. Find a tree with a sweet berry bush touching it
2. Try to chop down the tree
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method thedarkcolour.futuremc.block.villagepillage.SweetBerryBushBlock.getPickBlock, parameter target
    at thedarkcolour.futuremc.block.villagepillage.SweetBerryBushBlock.getPickBlock(SweetBerryBushBlock.kt)
    at ht.treechop.common.util.ChopUtil.isBlockLeaves(ChopUtil.java:80)
    ...
```

**Comment by anabsolutesloth** [comment]
I personally experienced this, and suspected it might have been the bush.
Redirect to HT's Tree Chop mod author here: https://github.com/hammertater/treechop/issues

**Comment by criscky** [comment]
https://github.com/hammertater/treechop/issues/58
