### ISSUE TITLE
[BUG] *Metallurgic Infuser from Mekanism using 250 EU/t instead of the normal 5 EU/t*

### ISSUE THREAD

**Issue by Relomas** [Minecraft-Eternal/MC-Eternal-1.12#404]
### Description of the Bug

Metallurgic Infuser for some reason uses 250 EU/t instead of the 5 EU/t.

### Expected Behaviour

Metallurgic Infuser uses 5 EU/t

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
This is an intentional spike in power usage to make Mekanism require some decent setup to get into.
