### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by tagrinnell** [Minecraft-Eternal/MC-Eternal-1.12#405]
I'm trying to fix an issue where the game will crash before even compiling the mods.  I've tried fully uninstalling Minecraft, Curseforge, MC Eternal, as well as repairing everything and using different modloaders.

The error code is "Exit Code: 0"

Please help

**Comment by anabsolutesloth** [comment]
Go to the discord for help with this, and provide the crashlog there.
