### ISSUE TITLE
[SUGGESTION] ME cables quest are white instead of fluix

### ISSUE THREAD

**Issue by Caralamelia** [Minecraft-Eternal/MC-Eternal-1.12#406]
### Description of Suggestion

Why?
![javaw_5ACyZVt1so](https://user-images.githubusercontent.com/48594117/138615360-70a96031-8792-4c3b-ab72-3d6cbdd7a810.png)
![javaw_LOx5DwdEpL](https://user-images.githubusercontent.com/48594117/138615362-4c939f48-f539-43ec-9903-9ec776f5b7dd.png)

### How does this improve the experience?

Removes frustration for those that dont tend to color their ME system on creating an item they will have to either trash of in

**Comment by anabsolutesloth** [comment]
Could add Color Applicator quest instead, it's good to know about the colored cables.

**Comment by Caralamelia** [comment]
That.. would be better
At the moment it just feels like an excuse to make white cables, maybe just changing the quest into requiring any of the colored versions instead of just white would do it

**Comment by anabsolutesloth** [comment]
AE2 questline has been overhauled as of MCE 1.6, Color Applicator quest has been added.
