### ISSUE TITLE
AmbientSounds 3 causing game freezes during thunderstorms

### ISSUE THREAD

**Issue by incomingnerd** [Minecraft-Eternal/MC-Eternal-1.12#41]
**Describe the bug**
When a thunderstorm occurred the sound effect for thunder would start, followed by a massive lag spike and the process would repeat. Exiting and re-entering the world had no effect - the bug persisted. After disabling AmbientSounds 3 the game now runs without lag again.

**Version of MC Eternal**
1.4.2 Beta

**To Reproduce**
1. Await a thunderstorm
2. Maybe encounter the bug?

**Additional context**
Running with 9GB RAM allocated.
Bug feels like GC triggering repeatedly - perhaps AmbientSounds is churning memory?

**Comment by anabsolutesloth** [comment]
Redirect to Ambientsounds 3 author here: https://github.com/CreativeMD/AmbientSounds/issues

**Comment by incomingnerd** [comment]
After tinkering with the Java args and doing other recommended things to reduce the RAM footprint the bug has not resurfaced. I'm going to call it a weird cross-mod interaction, as Vampirism was using an unreasonable number of cycles too. AmbientSounds may well have been the victim of someone else's memory leak, rather than the culprit. Closing for now,
