### ISSUE TITLE
[BUG] actually additions chestplates don't exist 

### ISSUE THREAD

**Issue by TylorBane** [Minecraft-Eternal/MC-Eternal-1.12#411]
### Description of the Bug

actually additions chestplates seem to have disappeared or something, they just dont exist. the only one that IS there is Palis or the "lapis" one.

### Expected Behaviour

for them to exist XD

### Modpack Version

1.5

### Screenshots

https://cdn.discordapp.com/attachments/336697507260268555/903022159637671936/unknown.png
https://cdn.discordapp.com/attachments/336697507260268555/903024023485689957/unknown.png

**Comment by criscky** [comment]
for what i know it's intented

**Comment by TylorBane** [comment]
what? intended? why? how could this be intended?
