### ISSUE TITLE
[BUG] cyclic tree harvester leaves "glitched" blocks from tree chopping mod

### ISSUE THREAD

**Issue by M3wM3w** [Minecraft-Eternal/MC-Eternal-1.12#414]
### Description of the Bug

After a while, the tree harvesting machine leaves "glitched" pillars of blocks,
that drop nothing and disappear when manually mined. 
The blocks seem from some recently added tree chopping mod.
They clog up the farm until no trees can grow anymore.
The saplings used were spruce.

### Expected Behaviour

Tree farm properly working.

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
This should be fixed whenever Treechop updates and we update the mod in the pack, as currently the Fakeplayer Chopping config that was supposed to be implemented is bugged.

**Comment by anabsolutesloth** [comment]
almost certainly fixed in MCE 1.6 now that treechop has been updated.
