### ISSUE TITLE
plant gatherer do not collet the items on Mc Eternal

### ISSUE THREAD

**Issue by ROMPEFUEGOS** [Minecraft-Eternal/MC-Eternal-1.12#415]
### Description of the Bug

This object must collect the items of the plants or trees that it fells. For example, if you cut down a tree, it should give you wood, apples, and saplins at the very least. But in the eternal MC, there is no way I will give you these items.
Who knows how to fix this? any way to modify the files?

### Expected Behaviour

1. you give it energy and a tree
2. I should cut it down
3. keep items in inventory

### Modpack Version

Mc Eternal 1.5

**Comment by anabsolutesloth** [comment]
Bug with the Treechop mod, it will be fixed when the mod next updates and we update the mod in the pack.
