### ISSUE TITLE
[BUG] *Replace with brief description of the issue*

### ISSUE THREAD

**Issue by Its-Poppy** [Minecraft-Eternal/MC-Eternal-1.12#418]
### Description of the Bug

When placing AgriCraft Grates in a certain rotation you can use Excavate with a Tinkers construct Hatchet. Pac man pet can be used to create a semi infinite loop (as long as you have food and cookies for pac man) where the hatchet will infinitely mine the gates. Durability does impact this, but with unbreaking it becomes endless. 
![image](https://user-images.githubusercontent.com/94018894/141011182-ae410eab-92a3-4fd6-ba73-47503d30e738.png)
https://cdn.discordapp.com/attachments/776178113645117471/907747826673532998/Infinite_TC_XP_Glitch.mp4

### Expected Behaviour

Expected to break the greates and drop them on the floor like items. Durability removed from hatchet and hunger depleted as normal. all joined blocks of matching types to be mined as well using excavate. 

### Modpack Version

1.5

### Screenshots

![image](https://user-images.githubusercontent.com/94018894/141011590-7870e05e-e866-4792-9ff8-070005982de7.png)
https://cdn.discordapp.com/attachments/776178113645117471/907747826673532998/Infinite_TC_XP_Glitch.mp4

### Extra Info

LagBGone

**Comment by anabsolutesloth** [comment]
Forward to Agricraft github probably, or OreExcavation if they even have one that has 1.12 and they still work on it
