### ISSUE TITLE
Tunneling Device and Sonic Boom

### ISSUE THREAD

**Issue by NeroToskani** [Minecraft-Eternal/MC-Eternal-1.12#420]
### Description of the Bug

Putting Sonic Boom on a Portable Tunneling Device from @DungeonTactics enables the function of destroying ANY Block in the game besides Bedrock. Even borderblocks from private pockets etc.
On top the destroyed block can be looted - only exception Portal Frames like end portal etc.

### Expected Behaviour

Get Portable Tunneling Device 
Get Sonic Boom enchant
Enchant Portable tunneling device with sonic boom
Go to the blocks you want to be removed for example high end tinker ores
Place a destrucatble stone like cobblestone onto the ore
Right click with the tunneling device onto the cobblestone
The device destroyes 3x3x2 and you get the tinker ore 

This is applicable for all blocks besides Bedrock
even stuff like Betweenlands SLudge dungeon and so on

### Modpack Version

1.5

### Extra Info

DungeonTactics
DT-0.16.9

**Comment by anabsolutesloth** [comment]
what the fuck
well mods funny i guess :V
