### ISSUE TITLE
Windows 11 port over from windows 10

### ISSUE THREAD

**Issue by CoryNB** [Minecraft-Eternal/MC-Eternal-1.12#422]
### Description of the Bug

I was looking for a launcher that works for modded Minecraft. I have a windows 11 laptop for me that meets the needs for this modpack, but curseforge/overwolf have not done a proper interface for windows 11. This resulted in me using an older launcher, the FTB launcher. this worked, but I found no pack codes for it. please find a way around the windows version issue until it is resolved.

### Expected Behaviour

N/A

### Modpack Version

1.5

### Screenshots

N/A

### Log

N/A

### Extra Info

extra mods were aroma mining world and xray mod. they worked well in helping me throughout the game.

**Comment by anabsolutesloth** [comment]
Please don't ask this type of question here :V, this Github Issues page should be reserved for bugs in the modpack, not your personal problems, those are more suited to ask in the MC Eternal Discord.
That being said, i'll cut down the chase for you, [MultiMC](url) is probably your solution, if it does not work, then you have no option but to wait, Windows 11 is still far too new for anyone to have anything very substantial on it.
