### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by ghost** [Minecraft-Eternal/MC-Eternal-1.12#425]
hello bro, i love mc eternal very much!But i encounter a problem when setting a server ,canyou help me with it. this is the clash-report:
https://github.com/XinChenzi/clash_report

In fact, the problem is that when I quit the game and tried to connect to the server again, the server crashed. But every time I turn on the server and enter for the first time, there is no problem.

**Comment by anabsolutesloth** [comment]
Set these two things to `false` in foamfix.cfg
```
B:fixWorldEntityCleanup=true
B:fasterEntityDataManager=true
```
Please check the discord for crashes first, and if instructed to please forward it here.

**Comment by ghost** [comment]
> Set these two things to `false` in foamfix.cfg
> ```
> B:fixWorldEntityCleanup=true
> B:fasterEntityDataManager=true
> ```
> Please check the discord for crashes first, and if instructed to please forward it here.

im sorry, and thanks a lot
