### ISSUE TITLE
[SUGGESTION] Buff/Debuff thorium oxide Nuclearcraft fuel to be more in line with other fuels

### ISSUE THREAD

**Issue by PatchyDragon** [Minecraft-Eternal/MC-Eternal-1.12#427]
### Description of Suggestion

After nearly blowing up one of my supposedly safe reactors with TBU-Oxide fuel, I realized there was something off in this modpack about the way Nuclear fuels work. Doing some digging, I discovered that at some point in the 1.4 update, the final (best in class) entry for each type of fuel had gotten a buff/debuff combo where it produces roughly twice the heat, but also roughly twice the energy.... Except TBU-Oxide, which got the double heat, but no energy buff.

Now while I of course don't want a fuel that can be grown using mystical agriculture to be nearly as powerful as Plutonium's HEP-241 Oxide getting a 100x buff in the modpack (it was buffed from 924 RF/t base to a whopping 8000 RF/t before multipliers), I feel like if Thorium oxide is also getting hit with the debuff stick, it should maybe have some kind of benefit as well to be more in line with others... Or perhaps it should just go back to being boring and weak, since it's one of the earlier fuels you can unlock.

### How does this improve the experience?

This would improve the consistency in the modpack's Nuclearcraft tweaks, and make the slow process of oxidizing your Thorium fuels before using them worthwhile, rather than just generating insane levels of extra heat to no benefit to the reactor aside from the vanilla +30% power generation over its non-oxide part in a regular fission reactor.

**Comment by anabsolutesloth** [comment]
NuclearCraft reactors will probably be directly buffed soon by power gen multiplier, whenever i get around to testing it, and will probably have all the altered fuel values reverted to defaults when that change occurs.

**Comment by PatchyDragon** [comment]
> NuclearCraft reactors will probably be directly buffed soon by power gen multiplier, whenever i get around to testing it, and will probably have all the altered fuel values reverted to defaults when that change occurs.

Ooh, that's a solution too! That'd help make other mod packs' generators viable as well. Maybe even a reason to use the Rainbow Generator if that's affected? 

I just desperately do not want to do the energy bees that make 2.4B RF/t. Those are so silly.

**Comment by anabsolutesloth** [comment]
Energy Bees will be nerfed, eventually, likely by gating.

**Comment by anabsolutesloth** [comment]
NC reactors have been global buffed and tinkered fuel values restored to defaults as of MCE 1.6.
