### ISSUE TITLE
Crashing when pulling an Antibarrel from YABBA

### ISSUE THREAD

**Issue by SoftGuardian** [Minecraft-Eternal/MC-Eternal-1.12#429]
I had a mob farm going a long time ago and my antibarrel was full so I broke the old one and put into my AE2 storage and made a new one. I had some vampire stuff there so I tried to take it back and when ever I click it on the crafting terminal it takes 2s then crashes

![2021-11-24_14 42 07](https://user-images.githubusercontent.com/73778546/143269545-b32db309-5bcd-46f9-b96a-7085e7e78c26.png)

**Comment by anabsolutesloth** [comment]
Use an Export Bus + Fuzzy Card to get it out.
On the Discord, we seriously do not advise using the Antibarrel as storage, only as a trash filter basically.
