### ISSUE TITLE
[BUG] Chance Cubes crashed at initialization

### ISSUE THREAD

**Issue by ShockedCoder** [Minecraft-Eternal/MC-Eternal-1.12#431]
### Description of the Bug

Cannot go past initialization, because Chance Cubes crashes.

### Expected Behaviour

1. Start game.
2. It initializes.

### Modpack Version

1.5

### Log

https://paste.gg/p/anonymous/d9ed1c7a5b4447928ef2346bce3371ef

### Extra Info

Extra Mods: cc-tweaked-1.12.2-1.89.2.jar, plethora-1.12.2-1.2.3.jar, nbtperipheral-1.1.jar (Happened before I even added these mods)

**Comment by anabsolutesloth** [comment]
Probably corrupt install or something, or your Java being funny.
