### ISSUE TITLE
[BUG] Wrong zinc crafts when using MA essence

### ISSUE THREAD

**Issue by idankaizer** [Minecraft-Eternal/MC-Eternal-1.12#434]
### Description of the Bug

Whenever crafting zinc using zinc essence from Mystical Agriculture the output is from Immersive Intelligence when in fact that zinc doesn't show up in JEI and whenever it enter a player's inventory turns into Tech Reborn Zinc (the right kind), this correction does not happen naturally within the ME System which breaks recipes. 

### Expected Behaviour

Use MA essence to craft zinc
Zinc crafted is of the wrong kind
Zinc changes mods while in player inventory
Breaks crafting chains

### Modpack Version

1.5

### Screenshots

![javaw_8Kh7uC8VXD](https://user-images.githubusercontent.com/96271483/146470438-a323a33e-dd6d-4574-802f-f220fbe38c3c.png)
![javaw_9C2LcE5daK](https://user-images.githubusercontent.com/96271483/146470442-b83437fc-57dc-4333-9c50-5175058a0d29.png)
![javaw_8HyWFFqg0f](https://user-images.githubusercontent.com/96271483/146470443-81662502-5fd9-4be3-bdce-ee12ec6c9942.png)

**Comment by anabsolutesloth** [comment]
You can't blame anything but oredictionary for it "outputting the wrong type of zinc".
This is not a problem, if you want to automatically get stuff to convert and make it produce the "right kind", use a Conveyor Belt from Immersive Engineering and pump the items onto it, they will be dropped in the world and by the InstantUnify unification event, becoming the "right kind".

Applied Energistics patterns can have inputs overridden manually, you are NOT limited to what JEI elects put into them :v
