### ISSUE TITLE
[BUG] Fossils and archeology revival plants don't spread/grow

### ISSUE THREAD

**Issue by sauphle** [Minecraft-Eternal/MC-Eternal-1.12#435]
### Description of the Bug

1: Some plants from the Fossils and archeology revival mod don't spread when bonemealed on loamy grass. meaning it's hard to get more duisbergia in a moor. I have tried bonemeal on every single flower on loamy dirt and none of them spread when they usually spread fine on regular grass.
2: All four saplings from the mod also disappear whenever I try to grow them on loamy grass.
3: Ancient ferns also don't spread 

### Expected Behaviour

1: When I bonemeal the plant it will spread randomly around where the plant was bonemealed
2: When I bonemeal the sapling it grows into a tree
3: When I plant ferns under leaves they spread to the next available grass block after fully growing

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
Yeah this is just an inherent issue with the mod, there is no way we can fix this, forward it to F&A's github if you want it to be fixed.
