### ISSUE TITLE
[BUG] *Lag multiplayer*

### ISSUE THREAD

**Issue by para302** [Minecraft-Eternal/MC-Eternal-1.12#436]
### Description of the Bug

MC eternal lite 
English
when I look at a player the game clicks and the tps are irregular.
I've used google translator.
Italian
quando guardo un player il gioco scatta e i tps sono inregolari.
Spagnolo
los tps del bajan cuando miro a otro jugador y es solo en esa ocasion.

### Expected Behaviour

Fps drop

### Modpack Version

1.3.8

### Screenshots

![2021-12-24_22 57 11](https://user-images.githubusercontent.com/96667670/147394532-9cef6a99-bc53-4a19-9ad5-91bedd3d7bd2.png)
![2021-12-25_23 15 00](https://user-images.githubusercontent.com/96667670/147394533-40504330-d486-4f6f-b53d-8a58d573fea3.png)
![2021-12-25_23 15 04](https://user-images.githubusercontent.com/96667670/147394534-b870f079-7fcd-465c-8a7d-e23760256af5.png)

### Extra Info

Bonsai Tree,performat

**Comment by anabsolutesloth** [comment]
Please head to the MCE Discord for future problems like this.

You are playing MC Eternal Lite, yes? if so, open `ebwizardry.cfg` at the following filepath:
`[MC Eternal Install]/config/ebwizardry/`
And adjust the following setting in that file to `false`:
`# Whether to use custom animations for players casting spells. Disable this option if it conflicts with other mods that add player animations.
B:spellcastingAnimations=true`

**Comment by para302** [comment]
it does not work
