### ISSUE TITLE
Between lands

### ISSUE THREAD

**Issue by Slither224** [Minecraft-Eternal/MC-Eternal-1.12#438]
### Description of the Bug

Between lands crashed as it was launching

### Expected Behaviour

launch

### Modpack Version

1.5

### Screenshots

<img width="752" alt="image" src="https://user-images.githubusercontent.com/57966416/147817243-f5de3451-d881-4320-a0fa-25c14ff81926.png">

**Comment by anabsolutesloth** [comment]
Please go to the Discord for issues like this.
What is most likely is that you did not allocate enough RAM to the modpack, if you do not know how to do this on Curseforge app, look around, google it, or do `!ram` in the #bot-commands channel of our Discord.
