### ISSUE TITLE
All mobs spawn with the same name and are buffed

### ISSUE THREAD

**Issue by tyler813** [Minecraft-Eternal/MC-Eternal-1.12#440]
### Description of the Bug

All mobs spawn in with the name" Lost Desert Assassin", and are super buffed. I can't find any information as to what mod this is from. All mobs even modded have this name and the increased health, speed, and attack damage. 

### Expected Behaviour

Mobs should spawn with regular stats and unnamed...

### Modpack Version

1.4.4 RC-1.5

### Screenshots

https://imgur.com/a/75OwbjB

**Comment by anabsolutesloth** [comment]
Do you have Optifine
also god dammit don't write both the example versions as the version, that's not fockin useful :V

**Comment by tyler813** [comment]
I dont have optifine and the version is 1.5, sorry its my first time posting :)

**Comment by anabsolutesloth** [comment]
Send over your copy of the `spawn.json` file from `[MCE Install]/config/incontrol`, ideally via a paste site please.

**Comment by anabsolutesloth** [comment]
@tyler813 been a while, this fixed for you now or no?

**Comment by anabsolutesloth** [comment]
I will close this for now, sudden cutoff in the middle of a bug report is not exactly ideal, and it just clutters things.
