### ISSUE TITLE
[BUG] *WorldgenLag by diverse mods*

### ISSUE THREAD

**Issue by Laynord** [Minecraft-Eternal/MC-Eternal-1.12#443]
### Description of the Bug

Diverse mods as MalisysCore Tinkers alloying and more are causing worldgen lags that not only make the server lag a bit but freezes the client for a sec each time 

i have not been able to fix it is there a know way to do so 

( i downloaded the server pack from curseforge and launched it on a seperate pc using another on the same network to connect to it )

### Expected Behaviour

I would like for the server not to like each time i generate a new chunck :/

### Modpack Version

1.5

### Log

https://paste.gg/p/anonymous/4d53aa44affe448faa80f2b2c7f7b4a3

**Comment by anabsolutesloth** [comment]
Please go to our discord for this, it's much easier to help you over there.

**Comment by Laynord** [comment]
on thx
