### ISSUE TITLE
[BUG] Dischantment Generator recipe does not display Enchanting Table in center

### ISSUE THREAD

**Issue by Monkeyfat12** [Minecraft-Eternal/MC-Eternal-1.12#444]
### Description of the Bug

i was trying to craft the Dischantment Generator but when i put every thing in the crafting table it dosent craft 

### Expected Behaviour

1 get the materials to craft the Dischantment Generator 
2 click crafting table put the materials in the correct spots
3 the  Dischantment Generator to be crafted 

### Modpack Version

1.12.2

**Comment by anabsolutesloth** [comment]
I believe Quark Matrix Enchanting fiddling with the Enchanting Table code confuses it enough to not display the Enchanting Table required in the recipe, and instead display a blank slot, i should probably add a tooltip about that.
Anyway yeah, known problem, just not fixed, and it's just a JEI display issue, adding an Enchanting Table will make it work.

**Comment by Monkeyfat12** [comment]
i added the Enchanting table in the middle and still nothing happened

**Comment by Monkeyfat12** [comment]
i see thanks that fixed my issues

**Comment by anabsolutesloth** [comment]
i still need to fix this issue, so i'm gonna reopen it as a reminder

**Comment by anabsolutesloth** [comment]
fixed as of MCE 1.6.
