### ISSUE TITLE
crash on loding model manger

### ISSUE THREAD

**Issue by mohe5** [Minecraft-Eternal/MC-Eternal-1.12#445]
### Description of the Bug

hi.
i am have problem on mc etrnal
crash on loding model manger
iam us curse forge
crash log
[crash-2022-01-17_15.59.46-client.txt](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/7882446/crash-2022-01-17_15.59.46-client.txt)

### Expected Behaviour

i don' know

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
Not enough RAM was allocated to Minecraft.
Please go to our Discord for problems such as this one.
