### ISSUE TITLE
Fresh install crash?

### ISSUE THREAD

**Issue by RuNNerxJ** [Minecraft-Eternal/MC-Eternal-1.12#448]
### Description of the Bug

Just installed MC Eternal through curse forge and altered nothing, I click play and it boots up like other Mods would through loading etc. and I get this error: 
Minecraft failed to start!

An error during startup prevented Minecraft from starting

The following mod(s) have been identified as potential causes:
Unknown ( Before this said Electroblob Wizardry, i have the crash file for this one as well)

### Expected Behaviour

1. Click play
2. mod loads
3. play MC Eternal lol

### Modpack Version

1.5

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/98368372/150897982-17c9c119-0134-4abe-9db7-7acb914e89ef.png)

### Log

https://paste.gg/p/anonymous/60a8f3265c1f45ed8f199b6702c2b0db

**Comment by RuNNerxJ** [comment]
Electroblob Log
https://paste.gg/p/anonymous/c3d21f8bbfe6418d8773a021289f60f3

**Comment by RuNNerxJ** [comment]
I also cannot get to the discord? I did the alt verification and The discord is just blank
![Screenshot (2)](https://user-images.githubusercontent.com/98368372/150902360-5567e0f7-ded8-4664-b30e-046b56619003.png)
?

**Comment by anabsolutesloth** [comment]
You did not allocate enough RAM to Minecraft, allocate more through your launcher.
If you do not know how to do such, read the rules in our Discord server to gain proper access, and then do `!ram` in our #bot-commands channel.
If you require further assistance, read the above instructions and ask in the #client-questions-and-issues channel on our discord.
