### ISSUE TITLE
Cyclic XP duplication

### ISSUE THREAD

**Issue by incomingnerd** [Minecraft-Eternal/MC-Eternal-1.12#45]
**Describe the bug**
The Cyclic Experience Pylon can be made to generate infinite XP from nowhere by just messing with the GUI.

**Version of MC Eternal**
1.4.2 Beta

**To Reproduce**
1. Create a Cyclic Experience Pylon
2. Gain a couple of levels of XP
3. Place pylon on the ground and crouch on top to deposit XP
4. Access the pylon's GUI and cycle the mode to "Spray Orbs"
5. Wait for the tank to empty a bit and note the amount of XP in the tank
6. Click the mode button once more to cycle back to "Collect Orbs" - notice the tank has refilled back to the starting point
7. Repeat from step 4 to generate infinite XP!

**Expected behavior**
Whatever the pylon is doing with its internal state is clearly not consistent.

**Comment by cornehoskam** [comment]
Will be fixed in the next release!
