### ISSUE TITLE
[BUG] infinite black market chest and creative modifier 

### ISSUE THREAD

**Issue by DefendedAura** [Minecraft-Eternal/MC-Eternal-1.12#450]
### Description of the Bug

When you create a new team all your quest progress is reset so you can abuse leaving and rejoining teams to endlessly get the rewards, my friend did this on a server we played on and got 5 mil currency, 40 stacks of black market chests, and 30 stacks of creative modifiers

### Expected Behaviour

join new team
progress retains
no infinite op items

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
Unfortunately, this is unpatachable, it is a flaw with how FTB Quests is designed, so we can't do shite to fix it.
