### ISSUE TITLE
[BUG] *Duplication of items, "magnetic" on tool and "storage bag" anywhere in inventory

### ISSUE THREAD

**Issue by tedpeterson01** [Minecraft-Eternal/MC-Eternal-1.12#451]
### Description of the Bug

When you mine a block, it will duplicate that block into your storage bag (Cyclic) - but only if you don't have that block already anywhere in your inventory. I've also found that it will duplicate items you put into it as well, but only the first item it sees, not sure. Like, if something is stackable, and I put it in the tinker bench, then use the magnetic tool on that tinker bench, it will turn that one item into 2 items, next time into 4, then 8, blah blah.

### Expected Behaviour

This doesn't need explaining.

### Modpack Version

1.12.2

### Screenshots

not applicable

### Extra Info

I couldn't help but use this dupe and I kind of killed the game for myself.

**Comment by Linyx-Multi** [comment]
How does one replicate this? the method was rather confusing.

**Comment by tedpeterson01** [comment]
Uh, it's been awhile. have your tool have the "magnetic" property, and have
a "storage bag" in your inventory. Then, break down blocks that are placed
and you get two of them.

**Comment by anabsolutesloth** [comment]
fixed as of 1.6.1, charm's magnetic enchant (the one that was causing it according to testing) is disabled
