### ISSUE TITLE
[BUG] MC Eternal failing to start

### ISSUE THREAD

**Issue by Astrithr** [Minecraft-Eternal/MC-Eternal-1.12#452]
### Description of the Bug

When I try to start the modpack, the game loads all the way up until I get to the message seen in the image. I could remove the mod that's preventing it to start, but there's no name... When I click on the "get link" button or on the crash report link, nothing happens. I tried installing more than one versions and it's the same everytime. 

![Capture d’écran 2022-02-08 175904](https://user-images.githubusercontent.com/99296973/153089995-2010ca67-e70d-4d93-b0b1-8b6f8d976323.png)

I didn't add optifine in the mods folder just yet but I was planning to. 
I really hope I can get it to work, as MC Eternal is one of my favorite modpacks.

Thanks in advance for the help !

### Expected Behaviour

The game to start ?

### Modpack Version

Forge 14.23.5.2854 

### Screenshots

![Capture d’écran 2022-02-08 175904](https://user-images.githubusercontent.com/99296973/153089995-2010ca67-e70d-4d93-b0b1-8b6f8d976323.png)

**Comment by criscky** [comment]
go to discord for support for that kinda of stuff
