### ISSUE TITLE
Immersive intelligence electrolyzer multiblock doesn't form without steel blocks from immersive engineering

### ISSUE THREAD

**Issue by Keltas** [Minecraft-Eternal/MC-Eternal-1.12#453]
I am playing on MC Eternal version 1.5. I wanted to make electrolyzer to produce chlorine, however the multiblock doesn't form. Upon testing things out I've found out that the issue lies in the fact that, for the purpose of forming the multiblock, immersive engineering is not recognizing the ore dictionary blocks of steel from thermal foundation. It requires the blocks to come from immersive engineering to form the multiblock. These however are not accessible in the modpack. After replacing the 2 offending blocks using the /give command the multiblock forms successfully.

I've checked Immersive Intelligence issues page and this specific issue was found and apparently fixed in a later version of the mod. https://github.com/Pabilo8/ImmersiveIntelligence/issues/63

**Comment by anabsolutesloth** [comment]
If it's already been fixed in the mod, then it will be fixed when we update the mod in most likely the next MCE version,

Also, Chisel should be able to switch the Steel Blocks into the IE ones with in-world Chiseling, i swear i did it atleast once.

**Comment by anabsolutesloth** [comment]
same case as #387, was fixed in 1.6, doesn't even exist in 1.6.1
