### ISSUE TITLE
[BUG] Aurorian Dimension is not the Aurorian

### ISSUE THREAD

**Issue by LeTo-WL** [Minecraft-Eternal/MC-Eternal-1.12#454]
### Description of the Bug

Everytime I enter the aurorian (whether that be through AR or by using the /dimteleport command in a creative world), the aurorian seems as though it does not have any of the biomes or blocks that the aurorian should have. It looks like it's mainly Biomes O' Plenty biomes and normal minecraft biomes. keep in mind that I did add some mods to the modpack, so that might be the reason and I might be a complete idiot. sorry if this is the case.

### Expected Behaviour

Enter the Aurorian
look around
Aurorian does not look like the aurorian

### Modpack Version

1.5

### Extra Info

I did add a few extra mods; do not remember what they are. if this is not an issue in the base modpack, that solves my issue.

**Comment by anabsolutesloth** [comment]
Go to the discord and see the most recent message in the #faq channel, we have the fix there.
