### ISSUE TITLE
[BUG] Amber duplication with crafting

### ISSUE THREAD

**Issue by Vismis** [Minecraft-Eternal/MC-Eternal-1.12#457]
### Description of the Bug

You can use 4 Amber from Biomes O' Plenty to make Thaumcraft amber block. And then you can use that amber block to make 9 amber from Biomes O' Plenty

### Expected Behaviour

1. Craft an amber block from Thaumcraft with 4 of any amber
2. Put the amber block in the crafting grid and receive 9 amber from Biomes O' Plenty
3. Repeat indefinitely

### Modpack Version

1.5

### Screenshots

![image](https://user-images.githubusercontent.com/78375940/156883774-0d6eb73a-b1a3-4f6f-894c-48d05084bd4f.png)
![image](https://user-images.githubusercontent.com/78375940/156883780-b507a297-d22e-4796-b7e0-0c90dc7c1c3c.png)

**Comment by anabsolutesloth** [comment]
on my todo, will patch later probably.

**Comment by anabsolutesloth** [comment]
should be fixed properly as of MCE 1.6

**Comment by koalaspeed5** [comment]
> ### Description of the Bug
> You can use 4 Amber from Biomes O' Plenty to make Thaumcraft amber block. And then you can use that amber block to make 9 amber from Biomes O' Plenty
> 
> ### Expected Behaviour
> 1. Craft an amber block from Thaumcraft with 4 of any amber
> 2. Put the amber block in the crafting grid and receive 9 amber from Biomes O' Plenty
> 3. Repeat indefinitely
> 
> ### Modpack Version
>any 

Quote from koala5solution:

Hi i have a solution to the infinite amber glitch of (BoP) biomes o' plenty.
open your modpack. Mine looks like this.

C:\Users\Ihaveaname\Desktop\Dregora+More\scripts\Dregora_recipes.zs

Scroll down to the bottom of the script and find this:

//=================================

//BOP RECIPES & NAME CHANGES

//=================================

now scroll to the bottom of that section and hit enter to add a space and type this:

recipes.remove(biomesoplenty:gem:7); // BugFix - Removes Recipe - Fixes infinite Biomes O' Plenty Amber Gem Dupe

I hope i helps out with the solution to the infinite amber dupe glitch :)

I added more mods to my favorite one to play. im playing DregoraRlcraft :D 🤺🏰

thaumcraft, astral sorcery, tinkers construct, applied energistics and 20 more :D

Look up zenscripts. theyre in the script folder. its a notepad saved as .zs  :)

what i did was my solution. 
mabye make a new file-notepad- copy and paste this 

recipes.remove(biomesoplenty:gem:7); // BugFix - Removes Recipe - Fixes infinite Biomes O' Plenty Amber Gem Dupe

save the file name ambergembugfix.zs 
dont name it ambergembugfix.zs.txt  lol :)
