### ISSUE TITLE
wont load says unknown/the betweenlands mod has caused it to fail

### ISSUE THREAD

**Issue by man99helm99** [Minecraft-Eternal/MC-Eternal-1.12#458]
### Description of the Bug

wont load says unknown mod has caused it to fail 

### Expected Behaviour

load

### Modpack Version

1.5

**Comment by man99helm99** [comment]
![mc](https://user-images.githubusercontent.com/88583673/157888317-681d0d1e-7f1b-4fdc-aed8-04731327d289.PNG)

**Comment by man99helm99** [comment]
![mc1](https://user-images.githubusercontent.com/88583673/157889840-04e01286-3bdf-4442-9f5f-f129e0513dc5.PNG)

**Comment by anabsolutesloth** [comment]
you most likely did not allocate enough RAM.
please ask questions or for help with crashes in the Discord in the future.
