### ISSUE TITLE
[BUG] Crafting Recipe for the Dischantment Generator Incorrect in JEI

### ISSUE THREAD

**Issue by blearoyd** [Minecraft-Eternal/MC-Eternal-1.12#459]
**Description**
Recipe in JEI shows the recipe that is missing the Enchantment table in the center.
![image](https://user-images.githubusercontent.com/63148114/158336445-1e571bf1-6e51-4da0-8f81-77b09dfc8295.png)

**Comment by anabsolutesloth** [comment]
Known issue, will fix when not lazy.

**Comment by anabsolutesloth** [comment]
fixed in MCE 1.6
