### ISSUE TITLE
Server files from cursed forge crashes every time you try to start it

### ISSUE THREAD

**Issue by Linkunknown1827** [Minecraft-Eternal/MC-Eternal-1.12#461]
### Description of the Bug

I have been trying to create a mc eternal dedicated server and have been unable to get it to not crash. I got the server files from cursed forge. and it always crashes. i have create a forge server in the past.

### Expected Behaviour

server files download for 1.5 crashes when started

### Modpack Version

server 1.5

**Comment by criscky** [comment]
please join discord, and ask your question in the correct chat. The invite is in the curseforge page.
this issue tracker isnt for this kinda of thing
