### ISSUE TITLE
[BUG] *Replace with brief description of the issue*

### ISSUE THREAD

**Issue by MrPBeam** [Minecraft-Eternal/MC-Eternal-1.12#462]
### Description of the Bug

server has lag when eating, consuming potions and attacking but not server lag like rubber banding or movement.

its hard to explain we have good connection to the server but its like the modpack lags when trying to do certain things

### Expected Behaviour

log in 
attack a mob or try to eat
delay after animation from eating or attacking

### Modpack Version

1.12.2

**Comment by anabsolutesloth** [comment]
not enough info, ancient issue.
lag support should be handled on the discord ideally, or it could take a long time to get resolved for someone.
