### ISSUE TITLE
Failure with installing Eternal

### ISSUE THREAD

**Issue by LeMetios** [Minecraft-Eternal/MC-Eternal-1.12#465]
### Description of the Bug

When installing with Curse Forge suddenly comes the message "Missing file for mod "KubeJS" (ID: 238086) in database. Aborting installation." 

I have reinstalled Curse Forge and it still does not work. I can install any other modpack though.

### Expected Behaviour

See in the description of the bug

### Modpack Version

MC Eternal 1.5

### Screenshots

![Screenshot 2022-05-07 230005](https://user-images.githubusercontent.com/43504037/167271573-760dc21d-451e-4b64-93e7-218b0ecd2297.png)

**Comment by anabsolutesloth** [comment]
Curse killed their old API recently, so launchers are having problems downloading from it, nothing we can do about this.
Dunno why it's listing KubeJS as the fault point though, that mod isn't even in MCE.
