### ISSUE TITLE
can't run the modpack

### ISSUE THREAD

**Issue by bradreslam** [Minecraft-Eternal/MC-Eternal-1.12#466]
### Description of the Bug

when the modpack is loaded it says that minecraft failed to start it also sais that electrobob's wizzardy was the cause

### Expected Behaviour

i expected it to run just fine

### Modpack Version

1.5

### Screenshots

![Knipsel](https://user-images.githubusercontent.com/105541244/168419695-05d993b0-09be-4210-8e58-40a4cad71610.PNG)

### Extra Info

i only installed the modpack and no other packs when i try to click on the link it doesn't work and the get link button fails i don't know where i can find the crash file in the explorer

**Comment by anabsolutesloth** [comment]
go to the discord.
