### ISSUE TITLE
[BUG] Bag of Holding (XU2) and Block Placer (Cyclic) Item Duplication.

### ISSUE THREAD

**Issue by doggg9216** [Minecraft-Eternal/MC-Eternal-1.12#467]
### Description of the Bug

Moving the Bag of Holding from Extra Utilities 2 through the cyclic block placer via hopper causes them to stack.

Filling those stacked Bags of Holding and then splitting them causes any items inside to be duplicated.

### Steps to Replicate
1. Create 2 Bags of Holding.
2. Place a Cyclic Block Placer
3. Put a Hopper on top of the Block Placer.
4. Put the Bags of Holding inside the Hopper.
5. When you pull them out of the Block Placer, they will be stacked.
6. Fill the Bags of Holding with an item of your choice. 
7. Split the Bag of Holding stack to duplicate items.

### Expected Behaviour

I would expect the Bags of Holding to not stack. They are not stackable without the block placer.

### Modpack Version

1.5

### Screenshots

Example: https://streamable.com/4wmip7

**Comment by anabsolutesloth** [comment]
bruh.
might as well disable both of these, cyclic placers are apparently awful for fps, and golden bags are just buggy in general.

**Comment by anabsolutesloth** [comment]
this fixed now via golden bags being disabled, i think in 1.6 but is absolutely for sure now in 1.6.1
