### ISSUE TITLE
[BUG] ThaumicAugmentation breaks journeymap's automap feature

### ISSUE THREAD

**Issue by Famerates** [Minecraft-Eternal/MC-Eternal-1.12#469]
### Description of the Bug

outdated thaumicaugmentation breaks journeymap's automap feature so that automap just doesn't load the map. Tested by pregenerating chunks and then using automap feature. After updating thaumicaugmentation, automap works just fine.

### Expected Behaviour

Expect to load with no problem, but doesn't work. Logs show that error is caused by thaumicaugmentation, and issue is already resolved in updated version of thaumicaugmentation.

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
If it's already fixed in a TAug update, then it can be expected to be fixed in the next update to the pack, as TAug will be getting updated.
