### ISSUE TITLE
[BUG] Duplication Bug in MCE 1.5

### ISSUE THREAD

**Issue by Maengorn** [Minecraft-Eternal/MC-Eternal-1.12#471]
### Description of the Bug

Items and containers of items can be duplicated on death if they are enchanted with Soulbound and have a Spectral Anchor from Random Things on the same item. Bug was found when ender armor with inventory had both enchants and then I died, when I respawned I had two pieces of armor with all the items stored in the inventory.

**Steps to replicate**
1. Apply Soulbound to an item.
2. Add a Spectral Anchor to the same item.
3. Die.
4. Upon respawning you will have two of that item.

### Expected Behaviour

Upon death only one of the enchants to work so only 1 of the item(s) are received when respawning.

### Modpack Version

1.5

### Extra Info

Hi Adam! You said to leave you a note about the hat.

**Comment by anabsolutesloth** [comment]
bruh moment
guess i'll disable the anchors and say to use soulbound.
i would disable assorted enchants if they didn't cause an enchantment id shift with the custom content in the pack (lootcrates, moon loot, etc.), i think i have a way to hypothetically get around it, but it requires adding a particular crafttweaker addon.

**Comment by anabsolutesloth** [comment]
fixed as of MCE 1.6.
