### ISSUE TITLE
[BUG] Crashed when I opened the Intro Science tab of the Quest Book 

### ISSUE THREAD

**Issue by Lavaheart626** [Minecraft-Eternal/MC-Eternal-1.12#479]
### Description of the Bug

While testing 1.6 in the multiplayer server I encountered a crash when switching from the advanced Science tab of the quest book to the Intro to Science tab of the questbook. I was not able to replicate this crash.

### Expected Behaviour

1. Click on Intro to Science tab of questbook.
2. Basic Science tab of questbook opens.

### Modpack Version

1.6

### Log

https://pastebin.com/hnyTi1Jt

**Comment by anabsolutesloth** [comment]
Java-level crash, can't do anything with that log.
If it was just a one-off, leave it as a one-off, especially if it was Java-level.
