### ISSUE TITLE
[BUG] *Moon causes client crashes*

### ISSUE THREAD

**Issue by th3impasta** [Minecraft-Eternal/MC-Eternal-1.12#481]
### Description of the Bug

Exploring on the moon causes client crashes

### Expected Behaviour

1. Explore area around my lunar base.
2. Walk near a structure made of dark stone blocks.
3. Client crashes, wont fix itself by rejoining.

### Modpack Version

1.5

### Extra Info

I don't have access to logs

**Comment by anabsolutesloth** [comment]
if it's a client crash you would have access to the necessary logs :V
i know this issue is goddamn ancient at this point, but if you still have the logs, then give via paste service (github gist is a good option in this case)
i'll close this in about a week if there is no response.

**Comment by th3impasta** [comment]
Sorry typo i meant client disconnect

**Comment by anabsolutesloth** [comment]
If you can't give any logs, then just say that's the case :v

**Comment by anabsolutesloth** [comment]
clearly no information that can contribute to pinpointing the problem can be provided, closing.
