### ISSUE TITLE
[BUG] Crash on startup with, betweenlands

### ISSUE THREAD

**Issue by lliott** [Minecraft-Eternal/MC-Eternal-1.12#482]
### Description of the Bug

Crash when I launch the modpack from the curseforge application.

### Expected Behaviour

1. Launch MC Eternal with 7GB
2. Game main menu

### Modpack Version

1.12.2

### Log

https://paste.gg/p/anonymous/176154499a89494aa62e1f7cd4839a73/files/9af9265f74bc4e99a11fb2cec4bfaad9/raw

**Comment by anabsolutesloth** [comment]
You need to allocate atleast 8GB of RAM to MCE 1.4+, 10GB is the recommended amount however, this will likely be reducing somewhat when MCE 1.6 comes out, as some very heavy hitter mods on that front will be getting kicked out.
Our Discord is a better place to get a quick response with these sorts of problems, aswell as general gameplay questions, though i get it if you don't want to bother with that.
