### ISSUE TITLE
[SUGGESTION] Replace VanillaFix with LoliASM

### ISSUE THREAD

**Issue by TheAirBlow** [Minecraft-Eternal/MC-Eternal-1.12#487]
### Description of Suggestion

Listed as CensoredASM on curseforge.
Basically it's vanillafix but with a bunch of RAM optimisations in addition. It also includes MC bugfixes. Do it for Lite too plsplsplspls

### How does this improve the experience?
Helps performance on weaker systems :trollface:

### Screenshots
lazy, just check their ones on curse

**Comment by WaterMelwin** [comment]
pedo mod

**Comment by TheAirBlow** [comment]
> pedo mod

IDFC if the mod does the job perfectly.

**Comment by skirlez** [comment]
pedo mod

**Comment by WaterMelwin** [comment]
> 

👍

**Comment by th3impasta** [comment]
how about normal asm instead

**Comment by TheAirBlow** [comment]
> how about normal asm instead

what's the damn purpose? you just get update delays.

**Comment by anabsolutesloth** [comment]
if it's gonna bring these conflicts into MCE space and also be somewhat unstable, no :V
