### ISSUE TITLE
[BUG] Recipe missing for /dank/null

### ISSUE THREAD

**Issue by Veight** [Minecraft-Eternal/MC-Eternal-1.12#490]
### Description of the Bug

No recipe in JEI for /dank/null

### Expected Behaviour

There should be a recipe in JEI 

### Modpack Version

1.6

### Screenshots

![image](https://user-images.githubusercontent.com/4164457/201384347-192c350f-01d7-4d56-b3a6-e9527cc074c5.png)

**Comment by anabsolutesloth** [comment]
i am silly and accidentally removed the base tier 1 dank recipe, this has now been fixed.
