### ISSUE TITLE
[BUG] Computer components deleted when placed into boxes

### ISSUE THREAD

**Issue by th3impasta** [Minecraft-Eternal/MC-Eternal-1.12#494]
### Description of the Bug

Putting a computer in a cardboard box from Mekanism causes the computer to delete it's contents.

### Expected Behaviour

1. Place a computer and fill it with components
2. Put it in a Mekanism cardboard box
3. Place the cardboard box back down
4. Computer should have contents, but they are deleted

### Modpack Version

1.5

**Comment by anabsolutesloth** [comment]
can't fix in a proper manner, but can atleast blacklist from boxing and similar

**Comment by anabsolutesloth** [comment]
fixed as of 1.6.1, most OC blocks are denied from being boxed (and captured in similar tools) now
