### ISSUE TITLE
[BUG] Raven Counts for Seagull Bounty

### ISSUE THREAD

**Issue by Leothechosen** [Minecraft-Eternal/MC-Eternal-1.12#499]
### Description of the Bug

I killed a Raven, and my Bounty: Seagull mission completed,

### Expected Behaviour

1. Kill Raven
2. Bounty: Seagull mission doesn't complete

### Modpack Version

1.6.1

**Comment by anabsolutesloth** [comment]
not fixable as noted on the discord
