### ISSUE TITLE
Get rid of teleporting through blocks with the compass

### ISSUE THREAD

**Issue by JordanVarley** [Minecraft-Eternal/MC-Eternal-1.12#502]
### Description of Suggestion

While its cool to tp through blocks I now cant use laser relays from actually additions because they need the compass to change the way they flow but I can't since it just tps me to the other side of the relay.

### How does this improve the experience?

allows people to actually use the laser relays.

**Comment by anabsolutesloth** [comment]
you have WorldEdit, that's why compasses are doing this, not a base MCE problem.
