### ISSUE TITLE
Mc Eternal 1.6.1 will not load properly the first load

### ISSUE THREAD

**Issue by StrawBerryBossman** [Minecraft-Eternal/MC-Eternal-1.12#503]
### Description of the Bug

This is my first time loading it up so it requires a download. I get an error message half way through the download. 

### Expected Behaviour

To successfully load/download

### Modpack Version

1.61

**Comment by anabsolutesloth** [comment]
go to the discord for assistance with this ideally, or you can actually attach a crash report or log :v currently we have absolutely nothing to on, finding out why a large modpack is crashing is the most awful guessing game in the world, because it has far too many possible answers.
