### ISSUE TITLE
[BUG] *Ftb quest description issues*

### ISSUE THREAD

**Issue by Nothingness-Void** [Minecraft-Eternal/MC-Eternal-1.12#504]
### Description of the Bug

Knightly Aex and Knightly Sword in ftbquest quest description are same `Foe's Armored? Not as much of a problem!`

But in game Knightly Aex is to deal extera damage to unarmored targets and the Knightly Sword is extera damage to armored targets

### Expected Behaviour

Maby fix the quest description?

### Modpack Version

1.6.1

### Screenshots

![image](https://user-images.githubusercontent.com/55913486/210137521-8551da43-478c-4fd4-a3b3-73303bb171c7.png)
![image](https://user-images.githubusercontent.com/55913486/210137524-66bccf72-22a5-41b9-b702-9242166a4673.png)
![image](https://user-images.githubusercontent.com/55913486/210137540-c9ba0fb4-3b9f-46b9-a6ed-6e52b0103da8.png)
![image](https://user-images.githubusercontent.com/55913486/210137545-082e2d80-c59c-4f3c-bb49-98bb5fc59c34.png)

**Comment by anabsolutesloth** [comment]
will be fixed in upcoming PR, thank

**Comment by anabsolutesloth** [comment]
fixed in #522
