### ISSUE TITLE
[BUG] Infinite Black Quartz [DUPE]

### ISSUE THREAD

**Issue by InsectByte** [Minecraft-Eternal/MC-Eternal-1.12#506]
### Description of the Bug

So, you start with 4 black quartz.

Craft it into a block of black quartz.

Place this block into the SAG MILL, this gives you 9 black quartz dust.

These dusts can be converted back into black quartz by smelting or enriching.

5 Black Quartz profit per cycle.

### Expected Behaviour

Craft a black quartz block from for 4 black quartz.
Crush the block to obtain 4 crushed black quartz.

### Modpack Version

1.6.1

### Screenshots

![image](https://user-images.githubusercontent.com/72791212/210179860-8f76128b-6445-4831-934e-fabcea621686.png)
![image](https://user-images.githubusercontent.com/72791212/210179868-d0ec7bf7-e196-4d69-a2b5-2fbff4a2206d.png)
![image](https://user-images.githubusercontent.com/72791212/210179877-a3be6ffe-c20e-43c5-a2a1-138f1d82f68b.png)

**Comment by anabsolutesloth** [comment]
incredible jaopca behavior

**Comment by anabsolutesloth** [comment]
fixed for 1.6.2, i made the fix atleast 4 months ago but i just forgot to push it to the repository lmao
