### ISSUE TITLE
The solar tower on the server does not work. During construction, it works for a couple of seconds and the interface no longer opens, and crashes in the server console

### ISSUE THREAD

**Issue by MalenbkajaSosna** [Minecraft-Eternal/MC-Eternal-1.12#507]
[https://pastebin.com/qbyhHzea](url)

**Comment by anabsolutesloth** [comment]
please use the issue template in the future :V
this issue appears to root from IT expecting AR 2.0.0+, which we do not have, this will hopefully not be the case in the next major update. (not the next update)

**Comment by MalenbkajaSosna** [comment]
> пожалуйста, используйте шаблон проблемы в будущем: V эта проблема, похоже, связана с ИТ-специалистами, ожидающими AR 2.0.0+, которого у нас нет, мы надеемся, что это не произойдет в следующем крупном обновлении. (не следующее обновление)

I'm sorry, I don't often go through the github and I don't get along with the mod folders. I didn’t even think to go there, I advise you to add information about the template in the README
