### ISSUE TITLE
[BUG] a question about Mithminite Belt

### ISSUE THREAD

**Issue by lzsyxy** [Minecraft-Eternal/MC-Eternal-1.12#514]
### Description of the Bug

after wearing this armor the view seems to be that i am decelerated,and the faster ,the narrower  the view.is this a bug or deliberately?
sorry for disturbing you,but i have asked in discord,nobody give me an exact answer.
thanks for you time!
(i'm not clever enough to upload a gif.sorry!)

### Expected Behaviour

i want it back to normal

### Modpack Version

1.12.2

**Comment by anabsolutesloth** [comment]
This isn't really a question for us, it's one for the Thaumic Additions dev, if it is intentional, it's really stupid.
