### ISSUE TITLE
[BUG] Inv sync issus, when on LAN!

### ISSUE THREAD

**Issue by simonhat** [Minecraft-Eternal/MC-Eternal-1.12#519]
### Description of the Bug

When I play MC-Eternal, I don't have any new mods added to my client. ,

When I try moving items around in the inventory, they move, but when i wanna use them, they haven't actually moved, they didn't sync the action I was doing, 

I can get it to move if I was in a chest or other inventory, Then I'll it work,

Any fixes to that since it really annoying 

### Expected Behaviour

I think is happens when i use home

i ain't sure

### Modpack Version

1.6.1 New one

### Extra Info
There u has an video where i show the issus
[This the issus.zip](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/10776526/This.the.issus.zip)

**Comment by anabsolutesloth** [comment]
The source of this sort of issue is deep-rooted in Forge to my knowledge, but if it does happen, you can atleast cure it, relogging or changing dimensions are consistent cures.
Plenty of things can start this issue, but one consistent starter i found in my own gameplay was using the Spell Library keybind from Roots while not holding a Staff.

**Comment by simonhat** [comment]
> The source of this sort of issue is deep-rooted in Forge to my knowledge, but if it does happen, you can atleast cure it, relogging or changing dimensions are consistent cures. Plenty of things can start this issue, but one consistent starter i found in my own gameplay was using the Spell Library keybind from Roots while not holding a Staff.



I found that out late nat,

Since I was using Keybind "K"  for locking blocks to the right place and after that i found out the spell library wa tje issues,

But I'm happy 😊 to know that was the issus and it was confirmed 👌

Have an nice day
