### ISSUE TITLE
[BUG] *Replace with brief description of the issue*

### ISSUE THREAD

**Issue by Garick-10** [Minecraft-Eternal/MC-Eternal-1.12#524]
### Description of the Bug

instalo el modpack manualmente y a la hora de iniciar me dice que falta el CTM-MC1.12.2-1.0.2.31 , luego de instalar ese archivo me da problemas con el bountiful, que puedo hacer ?

I installed the modpack manually and when I start it says that the CTM-MC1.12.2-1.0.2.31 is missing, after installing that file it gives me problems with the bountiful, what can I do?

### Expected Behaviour

que iniciara el juego no da mas alla del mensaje de error
to start the game does not give beyond the error message

### Modpack Version

1.6.1

### Screenshots

![eternal fail](https://user-images.githubusercontent.com/132621744/236341844-f6e75a5b-637b-4645-b815-68e4e0b83314.PNG)

**Comment by anabsolutesloth** [comment]
please go to our discord for support with crashes.
