### ISSUE TITLE
why does Obfuscate mod in this pack?

### ISSUE THREAD

**Issue by alsodoze** [Minecraft-Eternal/MC-Eternal-1.12#526]
sorry to bother you. i've tried to add armourer's workshop mod by myself. find Obfuscate is a bit conflit with it. so i've quickly checked the mod list. it's a lib mod if i didn't remembered wrong, but find nothing depends on this mod, and then i removed it and modpack runs as usual. so, just out of curious, why does it in this pack?

**Comment by anabsolutesloth** [comment]
probably a remnant from a since-removed mod, though i don't know what mod, if you could track down which, that would be appreciated.

**Comment by alsodoze** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/obfuscate/relations/dependents?filter-related-dependents=3
all mods on curseforge that depends on this mod i guess, not much and about half of them are not in 1.12.2. you remember more about what mod was used be in the pack than me i think.

**Comment by alsodoze** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/obfuscate/relations/dependents?filter-related-dependents=3
all mods on curseforge that depends on this mod i guess, not much and about half of them are not in 1.12.2. you remember more about what mod was used be in the pack than me i think.
