### ISSUE TITLE
[BUG] *Stolen Quest Loot still attempts to give summoner orb*

### ISSUE THREAD

**Issue by Toadssalsa** [Minecraft-Eternal/MC-Eternal-1.12#531]
### Description of the Bug

Summoner orb from removed mod is still present in stolen quest loot droptable, replaced with a generic item.

### Expected Behaviour

Not getting tooltip item.

### Modpack Version

1.6.1

### Screenshots

![mnu1f0H](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/assets/146064535/d962fab6-b0a4-4639-aa71-96a4a8a5a05d)

**Comment by anabsolutesloth** [comment]
This is already fixed for the next release.
