### ISSUE TITLE
[BUG] *Crashing with the "The following mod(s) have been identified as potential causes: Unkown" txt*

### ISSUE THREAD

**Issue by Hnjooo** [Minecraft-Eternal/MC-Eternal-1.12#532]
### Description of the Bug

The world loads normally, but when i spawn the screen is black for a few seconds and then it takes me to the main menu with the text on the screenshot. I repaired and reinstalled the world but it didn't help. 

I checked, the world is corrupted for some reason, i can start another world without a problem but the one i played with my friends is corrupted, is there a way to fix it?

### Expected Behaviour

Played for almost 20 hours and then this started happening.

### Modpack Version

1.12.2

### Screenshots

![image](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/assets/146572490/998da37f-54e1-43b9-9e6d-2c9a6945906d)

### Log

[crash-2023-09-30_18.20.37-server](https://gist.github.com/Hnjooo/b293e9086e39281037fd69bac987c22d#file-crash-2023-09-30_18-20-37-server)

**Comment by yav12** [comment]
The log you linked is not the log, just the filepath. To upload a log, please visit [gist](https://gist.github.com) and drag your log into the window, create the gist, then share the link here. 
Additionally, did you visit the [discord](https://discord.gg/R7srPN8Z) before making an issue?

**Comment by SahanaBanana007** [comment]
I had this problem as well and tried redownloading the modpack and all that but it still wouldn't work.

**Comment by Hnjooo** [comment]
@yav12  I did check the discord but i didn't recieve any help or was allowed to type in any text channels. I updated the log, it should work now, if you know how to fix it, please tell me.

**Comment by anabsolutesloth** [comment]
you'll probably want to hang around the MCE discord for future issues, be sure to read the rules thoroughly, as you can't really get access without doing so.

as for this issue, it appears the entities tag of a chunk was corrupted somehow, manually fixing that is more work than it's worth, since you don't even get to know what chunk in what region file.
loading a backup and using that is probably your simplest solution.

**Comment by Hnjooo** [comment]
@anabsolutesloth Okay, thank you for your help, have a blessed life
