### ISSUE TITLE
[BUG] Grave key is nolonger enchanted

### ISSUE THREAD

**Issue by JamBlueberry** [Minecraft-Eternal/MC-Eternal-1.12#538]
### Description of the Bug

so me and a friend lagged out are mc server and now Tombstone keys randomly are eather enchanted or when dieing with a normal key makes it enchanted ? 
idk if it normal after dieing 268 times  

### Expected Behaviour

Die to anything  
Tombstone spawns key
Key is not enchanted 

### Modpack Version

1.6.1

### Screenshots

![image](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/assets/37358740/87ed4a8f-9609-4ba5-b27b-57310ff3c7ea)

### Extra Info

Hosting on Shock bite  Forge_1.12.2_14.23.5.2860

**Comment by anabsolutesloth** [comment]
Grave Keys being enchanted frequently is a Halloween thing in Corail Tombstone, it's weird, but it's impossible to disable.
They can be enchanted sometimes when respawning if you've leveled up the Jailer perk from Corail's Knowledge of Death menu,
but typically, Grave Keys can be enchanted in two other ways that do not involve dying, which is crafting them with a specific reagent (by default, an Ender Pearl, it is that in MCE, for the record), or by using the Key on a Decorative Grave which currently has a Soul.

Ultimately, this is not an issue by any means, just some weird quirks in Corail Tombstone. (that i am not much of a fan of)
