### ISSUE TITLE
[BUG] NullPointerException

### ISSUE THREAD

**Issue by Kn0wnG1itch** [Minecraft-Eternal/MC-Eternal-1.12#545]
### Description of the Bug

*IN CHALLENGE MODE
When the attack animation starts from a skeleton with a bow, as soon as the bow starts raising to shoot, this is sent in chat: "[CHAT]  cERROR: java.lang.NullPointerException" No other issues concerning fps, tps, or performance in general. Only happens when in challenge mode. I've tried looking through the 3 CT scripts but I can't read code so it was of no benefit.

### Expected Behaviour

For no [CHAT]  cERROR: java.lang.NullPointerException to occur.

### Modpack Version

1.6.2

### Extra Info

Nothing appears in the debug log nor normal logs. Just the chat "[CHAT]  cERROR: java.lang.NullPointerException" (which appears in the log itself ofc but nothing else) I couldn't find any direct info regarding issue tracking with these newer releases, apologies if otherwise.

**Comment by anabsolutesloth** [comment]
known issue, it happens due to an issue on my part the Enchanted Grave Key denial Event handler, i messed up the order some checks should be going in.

see this commit for changes required to fix: https://github.com/Minecraft-Eternal/MC-Eternal-1.12/commit/6bb6ac2d7abe797c3be4d58e8b0c46b4531979f4

**Comment by anabsolutesloth** [comment]
1.6.2.2 is now released, which fixes this bug.
