### ISSUE TITLE
[BUG] * crafttweaker Tooltip*

### ISSUE THREAD

**Issue by Jowanny** [Minecraft-Eternal/MC-Eternal-1.12#549]
### Description of the Bug

After I connect to my self-hosted server, this message appears: 
ERROR: [crafttweaker]: Error Executing {[0:crafttweaker]: Tooltip.zs}: 1. caused by java.lang.ArrayIndexOutOfBoundsException: 1

I don't know if it is because of this error but the server sometimes runs 3700 ms after what is not bad but suddenly it becomes 27000 ms. sometimes a restart of the server helps. at first I had removed the -server from the LunchServer.bat, then it worked for a while. The server has not yet used all the system resources.

### Expected Behaviour

that the error message no longer appears and that the game is running constantly

### Modpack Version

client and server 1.6.2.2 

### Extra Info

Extra Mods: None
both systems are windows 10 no vms and the server uses the jdk-8u202-windows-x64 because the 17 and above do not work

**Comment by anabsolutesloth** [comment]
The error from Tooltip.zs is entirely separate from your performance issue, and a known thing which i have found a way to resolve, and it will be so come the next version.

As for your performance issues, i don't think the necessary details to figure them out are present, it would be preferred if you could come to the MCE discord if you wish to resolve it, as we can provide very active support there, with more than just one mind, though i can understand if you are averse to that.

**Comment by Jowanny** [comment]
The performance problems come from my Kaspersky. Since I had no problems with other mc mods and an older version of Eternal with the same settings. I didn't think of it immediately.
