### ISSUE TITLE
[BUG] Small issue: Modpack crashes on startup (Fix in description)

### ISSUE THREAD

**Issue by 1nd1r4** [Minecraft-Eternal/MC-Eternal-1.12#550]
### Description of the Bug

SerializationIsBad is bugged on version 1.5.0. It attempts to download a config file and fails. The issue has been fixed in version 1.5.2, which can be downloaded on their GitHub page. Please update the mod in the modpack.

### Expected Behaviour

SerializationIsBad on current version -> Modpack starts.

### Modpack Version

1.6.2.2

**Comment by anabsolutesloth** [comment]
this is a known problem, an update will be pushed relatively soon

**Comment by ianwcart** [comment]
still waiting on a fix

**Comment by yav12** [comment]
you can fix it yourself by updating the mod `serializationisbad` in your modpack instance, that should resolve it

**Comment by ianwcart** [comment]
Thanks worked as you said.

**Comment by anabsolutesloth** [comment]
fixed in 1.6.2.3 (which has been out for a while from the writing of this comment)
