### ISSUE TITLE
[SUGGESTION] "Serializationisbad" is not updated to the most recent version in current modpack

### ISSUE THREAD

**Issue by altithedragon** [Minecraft-Eternal/MC-Eternal-1.12#551]
### Description of Suggestion

One of the mods included in the MC Eternal modpack (1.12.2) by the name of "Serializationisbad", has an update to 1.5.2 released on 3/16/2024, but by default, the previous version (1.5) is downloaded instead.
Manually updating seems to work. 
In Curseforge: [My Modpacks > MC Eternal > Mods > Serializationisbad > Versions > Install (On version 1.5.2)]

### How does this improve the experience?

Some users may crash to desktop with error code 1 if the mod does not update to the most recent version as needed.

### Screenshots

![image](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/assets/167466305/808d6577-95da-4c74-9eb7-8b9a539da857)

**Comment by anabsolutesloth** [comment]
yes, this problem is very known, shown up many times on the MCE discord, it will be a part of the next update.

**Comment by anabsolutesloth** [comment]
1.6.2.3 has been released (for a while now) and resolves this
