### ISSUE TITLE
[BUG] When I try to enter the modpack, the error appears due to the thaumic augmentation mod.

### ISSUE THREAD

**Issue by gmaiafe** [Minecraft-Eternal/MC-Eternal-1.12#555]
### Description of the Bug

Não entra no modpack por que da erro no mod thaumic augmentation

### Expected Behaviour

que entre sem problemas

### Modpack Version

1.12.2

### Screenshots

![image](https://github.com/user-attachments/assets/30d898e4-8d7b-4651-825d-24c7b85037c6)

**Comment by anabsolutesloth** [comment]
the crash report would be necessary to even have a clue as to what's up with it.
our discord is a more appropriate place for these sorts of issues, as you'll get a much quicker response there, and not just from the staff team.
i'll leave this open for a few days.
