### ISSUE TITLE
o modpack está crashando

### ISSUE THREAD

**Issue by EpiritoPoderoso** [Minecraft-Eternal/MC-Eternal-1.12#58]
Abri o modpack Mc Eternal hoje por volta de 12hrs, quando ele terminou de abrir deveria ie para a pagina do jogo mas apareceu uma tela de crash no lugar da principal do jogo.
Mostrou que os seguintes mods não estavam funcionando:
JEI-Just Enough Itens
TConstruct- Tinkers´ Construct

Relato que isso atrapalhou tudo oq tenho para fazer nele, e gostaria que tomasse uma providencia e corrigisse o erro dele por favor

**Comment by anabsolutesloth** [comment]
The following is translated via https://translate.google.com/
Lo siguiente está traducido a través de https://translate.google.com/
Utilice el inglés al informar errores.
Se requerirá un registro de fallas para rastrear la fuente del problema, utilice Hastebin para proporcionar el registro.
https://hastebin.com/

**Comment by criscky** [comment]
esse git é para relatar erros por conta do modpack, por favor, o você está relatando parece ser uma falta de memoria ram alocada, por favor, faça a mesma pergunta no nosso discord
https://discord.gg/mceternal
o minimo de ram para ser alocada nesse pack é 8gb ou mais para a versão mais recente (1.4.x)
