### ISSUE TITLE
Serverpack for 1.4.3

### ISSUE THREAD

**Issue by feathecutie** [Minecraft-Eternal/MC-Eternal-1.12#60]
With 1.4.3 being a release version on CurseForge, there should be serverpack available on CurseForge as for the previous release versions.

Of course it might already be added soon, just wanted to open this issue to keep track of it.

If the serverpack is not yet being worked on, I could try to create one following the style of the latest one (1.3.7), using the mods/configs/etc. from 1.4.3.

**Comment by criscky** [comment]
problems are being solved, the serverpack will be done when it's done, please dont keep asking, if you want more update please join discord

**Comment by feathecutie** [comment]
Thanks! Sorry for asking before having checked everywhere, I just hope this issue will at least clear some confusion/questions if someone happens to stumble over it.
