### ISSUE TITLE
[BUG] Mortar & Pestle to make pulverized coal

### ISSUE THREAD

**Issue by Flame1869** [Minecraft-Eternal/MC-Eternal-1.12#61]
**Describe the bug**
Using the Mortar & Pestle from DungeonTactic's + coal will make you pulverized coal.
This only works once as the mortar & pestle used durability. 
The recipe is bugged once 1 durability of the mortar & pestle was is used

**Version of MC Eternal**
1.4.3

**To Reproduce**
1. craft the stone mortar & pestle form DungeonTactics
2. use the mortar and pestle with some vanilla coal to make pulverized coal
3. you'll see it will only work once and when some durability is lost on the mortar & pestle, the recipe doesn't get recognized anymore

**Expected behavior**
Its expected the recipe would till work with lost durability on mortar & pestle

**Screenshots**
[Imgur upload](https://imgur.com/a/UtE66pP)

**Additional context**
n/a

**Comment by anabsolutesloth** [comment]
Will write a fix via Crafttweaker.
