### ISSUE TITLE
[BUG] Describe the bug in a single sentence

### ISSUE THREAD

**Issue by therealbill** [Minecraft-Eternal/MC-Eternal-1.12#67]
**Describe the bug**
Various AW2 SurvivalBuild structures are requiring a slab that has no texture and can not be crafted, though may rarely appear in generated structures. This leads to not being able to actually build the block in the Drafting Bench. 

**Version of MC Eternal**
1.4.3

**To Reproduce**
1. Go to 'Drafting Bench'
2. Click on 'Select Structure'
3. Search for and select 'SurvivalBuildManufactory1'
4. See the texture-free entries for "wooden plank"

**Expected behavior**
It should have blocks you can actually put in there.

**Additional context**

After some digging, it appears that in the .aws file for this (and several other structures in that list) some are listing the following:
`JSON:{blockState:{blockName:"minecraft:stone_slab",properties:{half:"bottom",variant:"wood_old"}}}`

This is the problematic block. I've been testing out just changing them to 
`JSON:{blockState:{blockName:"minecraft:wooden_slab",properties:{half:"bottom",variant:"oak"}}}`

and that seems to work fine. Essentially I changed it to a wooden slab w/variant of oak. With that (and a client/game reload ofc) I can put in the oak slabs and it looks and behaves fine.

A quick grep through the files in `config/ancientwarfare/structures/included/normal/SurvivalStructures` show the following structures try to use that "wooden" stone slab:
SurvivalBuildBlacksmiths.aws
SurvivalBuildChurchLarge.aws
SurvivalBuildGrainStore.aws
SurvivalBuildHouseMedium1.aws
SurvivalBuildHouseMedium2.aws
SurvivalBuildHouseSmall1.aws
SurvivalBuildHouseSmall2.aws
SurvivalBuildManufactory1.aws
SurvivalBuildManufactory2.aws
SurvivalBuildManufactory3.aws
SurvivalBuildManufactory4.aws
SurvivalBuildStoreBarn.aws
SurvivalBuildTavern.aws
SurvivalBuildTownCakeShop.aws
SurvivalBuildTownCourtsAndPrison.aws
SurvivalBuildTownLibrary.aws
SurvivalBuildTownManufactory.aws
SurvivalBuildTownMetalWorker.aws
SurvivalBuildTownSawmill.aws
SurvivalBuildWatchTowerLarge.aws
SurvivalBuildWatchtowerSmall.aws
SurvivalBuildWaterMillManufactory.aws
SurvivalBuildWell.aws
SurvivalBuildWindmill.aws

Some of those are double slabs and would need to use that value, but so far changing those has allowed the structures I've tested to work not only in the Drafting Table but when being built from the resulting block.

Some notes about this problem:
The way the Drafting Table works is that you add the items to its inventory then it consumes them. I have not yet tested whether changing this on an active (partially "supplied" block) updates it in-place or if you have to restart the block. However, when you change/reselect the block from the list you do NOT get a refund of the consumed resources. So proper testing of that to be able to advise people of it would be good. I may try to get to that tonight after work.

Note on the "bad block": apparently if you find them in world generated structures they need a pickaxe to mine (tested this in a world w/cheats on to spawn them) - likely due to being classified as a stone one - and look fine *until harvested* when they get the black and purple checker texture. Something is funky w/that slab.

**Comment by anabsolutesloth** [comment]
Redirect to AW devs so it can be properly fixed by them: https://github.com/P3pp3rF1y/AncientWarfare2/issues
