### ISSUE TITLE
Dank Null Memory Leak/Freeze (Multiplayer)

### ISSUE THREAD

**Issue by Gibbles96** [Minecraft-Eternal/MC-Eternal-1.12#69]
**Describe the bug**
After extensive testing via Singleplayer and Multiplayer 1.4.3 (Quack Server files) testing, use of any Dank Null results in maxing out my RAM (regardless of the max I set it to in MultiMC) and causing the game to freeze for 10-20 seconds, unfreeze and then freeze again until I end the task via task manager. For some reason it did not cause issues in singleplayer, only in multiplayer.

**Version of MC Eternal**
MCE 1.4.3 (Multiplayer)

**To Reproduce**
1. Join 1.4.3 server
2. spawn in any Dank Null
3. mine a bunch of cobble to add items to the Dank Null
4. after a a little while of adding items to the Dank Null, the game begins to freeze due to memory leak.

**Expected behavior**
Dank Null holds items without freezing game in multiplayer.

**Screenshots**
N/A

**Additional context**
I have tried reinstalling the modpack and java. I have also tried different java arguments to no avail. 
There were no issues with the Dank Null's previous 1.7.90 version on servers and was curious on if the recent upgrade (1.4+) to 1.7.91 might have introduced a new issue alongside the newest version of Forge (also in a PR to be downgraded due to issues)

Also, the issue seems to be with the larger Dank Null's, the first 2 tiers only added a little hitching but once I hit the Iron tier and above it started the fatal freezing issues. The Emerald Null will very quickly cause the issue.

**Comment by criscky** [comment]
will check

**Comment by Gibbles96** [comment]
Update:
I went ahead and upgraded my ram to be sure the freezes weren't caused by max ram usage. I now think its just a 100% CPU bug when the item is in the players inventory in a server. I can play fine up until the moment I plop in a Dank Null in my inventory then it nonstop freezes (to reiterate, this bug is in servers, Dank Null still works fine in singleplayer for some reason)

**Comment by Gibbles96** [comment]
Update 2: I found a fix for the time being. The bug stems from some sort of corrupted player data in the server files. After deleting the player data for the problem player, the dank null is fine as well as the 100% CPU bug. Thanks for looking into it! :)
