### ISSUE TITLE
[BUG] Capsules can be used to duplicate chests and items,

### ISSUE THREAD

**Issue by Anacromacia** [Minecraft-Eternal/MC-Eternal-1.12#70]
**Describe the bug**
Capsules can be used to duplicate chests and items, due to the capture basenot taking the original items. 

**Version of MC Eternal**
Which version of the mod pack are you on?
1.4.3
**To Reproduce**
1. set down a capture base
2. put a chest onto it, 
3. use an unused capsule
4. the capsule should be closed, and working, but the chest is still there 

**Expected behavior**
it to vanish

**Screenshots**

**Additional context**

**Comment by criscky** [comment]
it took me a while to get to this, but i couldnt reproduce in the latest

**Comment by criscky** [comment]
i guess it was solved by some update
