### ISSUE TITLE
[BUG] multiplayer fatal error

### ISSUE THREAD

**Issue by Vojta7022** [Minecraft-Eternal/MC-Eternal-1.12#75]
**Describe the bug**
I am playing MC Eternal on Craftersland server. When I join the server, it immediately kick me out and say that fatal error occurred, this connection is terminated
The game didn't crash, it only says that and returns me to menu
I have 12gb of memory allocated and my PC has 32 gb
singleplayer is working normally
![Výstřižek222](https://user-images.githubusercontent.com/59890539/113843037-8d354f80-9793-11eb-8556-7cbf13b84b04.PNG)

**Version of MC Eternal**
Which version of the mod pack are you on?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by criscky** [comment]
for what you're saying it seems that on the server side
you prob need contact the server owner in that case

**Comment by Vojta7022** [comment]
There was a corrupted chunk. It is solved now.

Vojtěch Ponrt

Dne st 7. 4. 2021 16:31 uživatel criscky ***@***.***> napsal:
