### ISSUE TITLE
[BUG] Significant decrease in FPS in 1.4.3 vs 1.3.7.1

### ISSUE THREAD

**Issue by sealchan1** [Minecraft-Eternal/MC-Eternal-1.12#76]
After installing MC Eternal 1.4.3 and entering a newly created world, the video evidenced a notable increase in choppiness as compared to 1.3.7.1.  My FPS rate on my system went from 50 - 60 to 20 - 30.

I am running it on a Asus ROG Strix GL553VE and I am launching with Overwolf's CurseForge and giving 9GB of RAM.  My system is seeming to only provide about 8GB however.  This config is the same for 1.3.7.1.

My hope is that there are some set of performance issues that might be resolved to significantly improve this or a recommendation for a configuration change if not.

**Comment by criscky** [comment]
reduce your render view to 8 or 6 and go to our discord to grab args that can help with the GC
also if you're using optifine remove it

**Comment by sealchan1** [comment]
I'm  configured through CurseForge to dedicate 9GB to the game...while loading it looks like 8GB are being reserved...Task Manager indicates that Java has 9GB.  

Optifine is not installed.

Render distance settings and FPS...
12    20+
10    25+
8      30+
6      45+

I think I can live with render distance 8 and crank it down as needed underground in a pitch battle.

Thanks!


    On Wednesday, April 7, 2021, 07:33:18 AM PDT, criscky ***@***.***> wrote:  
 
 


reduce your render view to 8 or 6 and go to our discord to grab args that can help with the GC
also if you're using optifine remove it
