### ISSUE TITLE
[BUG] Astral sorcery perks wont unlock

### ISSUE THREAD

**Issue by Flame1869** [Minecraft-Eternal/MC-Eternal-1.12#82]
**Describe the bug**
After making the attunement altor plus the star fuguere, you jup on and the cutscene starts to play.
once dont the perks should be unlocked in you book, but it wont unlock.

**Version of MC Eternal**
1.4.3

**To Reproduce**
1. make attunement altar
2. discover the starsign so you see the blue sparks in the attunement altar
3.  (in my case i used starsign Discidia)
4. jump on the attunement altar and watch the cutscene 

**Expected behavior**
perks should unlock

**Screenshots**
the cutscene 
![2021-04-08_20 37 14](https://user-images.githubusercontent.com/75633209/114084005-fb6f3480-98af-11eb-836b-5a8407c32b0e.png)

perks wont unlock in the book
<img width="664" alt="perks missing" src="https://user-images.githubusercontent.com/75633209/114084145-222d6b00-98b0-11eb-8084-85d79dfac302.PNG">

**Additional context**
some user mentioned on the Discord:
_@1869Flame go to unidict config folder, open IntegrationModule.cfg and set astral integration to false_

i closed my game, changed the value, rebooted the game tried the whole attunement ritual again.
The right starsign wansnt in the sky so I could not test this yet (had to quit due to other curconstances)
(update: tested, didn't work either)

**Comment by Flame1869** [comment]
Update 9th april:
To make sure it was not an bug in my current save game, did a test today:
I created a whole new world and have redone the whole quest line from AS up till the attunement.

Sadly, the result was the same. The cutscene plays, but once it's done, the perks are not unlocked.

**Comment by Flame1869** [comment]
Marking the moment just before i jump on the Attunement altar, and marking the moment i get off the altar and quit:
doesnt seem to give much info either...

_[10:34:58] [Client thread/INFO]: [CHAT] <1869_Flame> jumping on!
[10:35:01] [Client thread/WARN]: NBT contains bad sneak behavior value ""; using default value instead
[10:35:03] [Client thread/WARN]: NBT contains bad sneak behavior value ""; using default value instead
[10:35:44] [Client thread/WARN]: NBT contains bad sneak behavior value ""; using default value instead
[10:35:47] [Server thread/WARN]: defineId called for: class com.mrbysco.instrumentalmobs.entities.EntityCymbalHusk from class com.mrbysco.instrumentalmobs.entities.EntityMaracaSpider
[10:35:50] [Server thread/INFO]: <1869_Flame> failed
[10:35:50] [Client thread/INFO]: [CHAT] <1869_Flame> failed_



full log here:

[Log.log](https://github.com/Minecraft-Eternal/MC-Eternal-1.12/files/6289515/Log.log)

**Comment by Mediocre-Charlotte** [comment]
I tested it, and it seems to have been caused by an incompatability between AS and Ido, since when I disabled Ido, I was able to attune myself just fine, although the camera was still a bit glitchy. I haven't seen anyone else test it though, so I am not 100% sure if that is the case. If a few other people could confirm that, that would be great!

**Comment by Flame1869** [comment]
Confirmed as @Mediocre-Charlotte mentioned.
i removed IDO mod and tested it again.
now the attunement works!

**Comment by Flame1869** [comment]
Solved in 1.4.3.1 as in that update Ido is removed
