### ISSUE TITLE
[BUG] DimensionalDoors going through doors put you 1 block lower, then falling/death.

### ISSUE THREAD

**Issue by EvgenyPoletaev** [Minecraft-Eternal/MC-Eternal-1.12#97]
**Describe the bug**
When traveling through doors in DimensionalDoors(only tested golden doors). it will put you 1 block lower than intended. In certain puzzles where there is no block **under** _SUPPORTING_ block, it will cause you to fall and die.

If there is a block under supporting block, then it will just clip you through block you are supposed to be standing on, and you will need to jump out to move again. 

**Version of MC Eternal**
1.4.3.1, _both_ server and singleplayer have same issue., 3 different computers in different households.

**To Reproduce**
Go through dimensional doors, 90-95% chance you will end up 1 block lower than intended on the other side.

**Expected behavior**
In previous version 1.3.4 that I played, you were always ending up at correct height level.

**Screenshots**
https://cdn.discordapp.com/attachments/655858176608174090/831730598354878484/unknown.png

**Additional context**
Another user reported this on discord:

Buk-Avea™ 🍞 - iuk ukleepaumn — Yesterday at 11:11 PM
:>
know issue, i found some causes, but duck said that he still have even with the one i found, so i'm not sure if there's more than one thing causing that

**end of bug description**

**Comment by EvgenyPoletaev** [comment]
https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/995

https://github.com/Advanced-Rocketry/AdvancedRocketry/commit/0950322e192f219d860b74eeb6de3b00bf8d5592

I searched everywhere and found this, maybe this gravity is the culprit?

**Comment by EvgenyPoletaev** [comment]
Spoke with Bread. Valkyrian Skies mod is likely causing it too.

**Comment by criscky** [comment]
fixed by #100
