### ISSUE TITLE
[BUG] Mirion ingredients don't alloy in tinkers' smeltery.

### ISSUE THREAD

**Issue by b0lshevik** [Minecraft-Eternal/MC-Eternal-1.12#98]
**Describe the bug**
Mirion alloy isn't created from the alloy ingredients.

**Version of MC Eternal**
1.4.3.1

**To Reproduce**
1. Put terrasteel, manasteel, cobalt, elementium and glass (or sand) in TiCon smeltery
2. Wait for materials to melt
3. Mirion doesn't alloy; the metals and glass just remain as separate liquids in the smeltery

**Expected behavior**
According to JEI the materials should alloy to mirion,

**Screenshots**

**Additional context**
I don't think smeltery fuel has anything to do with alloying, but just in case I tried replacing the blazing pyrotheum I was using with lava but received the same result. I didn't test all of the plusticminusbad fork of plus TiC but osgloglass seems to alloy normally. I don't see any related errors in the logs for MultiMC or when following the tail of debug.log from the server when smelting the materials. It's just as if the recipe doesn't exist even though JEI shows it. Mirion ingots can be smelted and molten mirion can be cast without issue so for the time being I can just trash the ingredients and use /give for the ingots. I looked over on the github for plusticminusbad but don't see the issue there.

**Comment by anabsolutesloth** [comment]
I believe there might be an incorrect fluid in the smeltery due to MoarTinkers, i can whip up a fix later.

**Comment by anabsolutesloth** [comment]
Fixed by #105
